"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { test } = require("node:test");

const root = path.resolve(__dirname, "..");
const appJs = fs.readFileSync(path.join(root, "public", "app.js"), "utf8");
const indexHtml = fs.readFileSync(path.join(root, "public", "index.html"), "utf8");
const stylesCss = fs.readFileSync(path.join(root, "public", "styles.css"), "utf8");

function functionBody(name) {
  const start = appJs.indexOf(`function ${name}(`);
  assert.notEqual(start, -1, `missing function ${name}`);
  const bodyStart = appJs.indexOf(") {", start) + 2;
  assert.notEqual(bodyStart, 1, `missing function body ${name}`);
  let depth = 0;
  for (let index = bodyStart; index < appJs.length; index += 1) {
    const char = appJs[index];
    if (char === "{") depth += 1;
    if (char === "}") depth -= 1;
    if (depth === 0) return appJs.slice(bodyStart + 1, index);
  }
  throw new Error(`could not parse function ${name}`);
}

function cssRuleBody(selector) {
  const start = stylesCss.indexOf(`${selector} {`);
  assert.notEqual(start, -1, `missing css rule ${selector}`);
  const bodyStart = stylesCss.indexOf("{", start);
  const bodyEnd = stylesCss.indexOf("}", bodyStart);
  assert.notEqual(bodyEnd, -1, `missing css rule end ${selector}`);
  return stylesCss.slice(bodyStart + 1, bodyEnd);
}

test("collab agent tool calls render as compact summary cards", () => {
  assert.match(appJs, /collabAgentToolCall:\s*"协作 Agent"/);
  assert.match(appJs, /function renderCollabAgentToolCall\(/);
  assert.match(functionBody("renderItemBody"), /renderCollabAgentToolCall\(item\)/);
  assert.match(functionBody("renderCollabAgentToolCall"), /collab-agent-card/);
  assert.match(functionBody("renderCollabAgentToolCall"), /collab-agent-raw/);
  assert.match(stylesCss, /\.item\.collabAgentToolCall/);
  assert.match(stylesCss, /\.collab-agent-card/);
});

test("live operation cards dock at the bottom and expose only the newest operation", () => {
  assert.match(appJs, /function currentLiveOperationEntry\(thread\)/);
  assert.match(functionBody("currentLiveOperationEntry"), /const turn = thread\.turns\[thread\.turns\.length - 1\]/);
  assert.match(functionBody("currentLiveOperationEntry"), /if \(!turn \|\| !isLatestTurn\(turn\) \|\| !isLiveTurn\(turn\)\) return null;/);
  assert.match(functionBody("currentLiveOperationEntry"), /if \(isOperationalItem\(item\)\) latest = \{ turn, item, sourceIndex: index \};/);
  assert.match(appJs, /function renderLiveOperationDock\(thread, previousKeys = new Set\(\)\)/);
  assert.match(functionBody("renderLiveOperationDock"), /currentLiveOperationEntry\(thread\)/);
  assert.match(functionBody("renderLiveOperationDock"), /live-operation-dock/);
  assert.match(functionBody("renderCurrentThread"), /const liveOperationDock = renderLiveOperationDock\(thread, previousKeys\);/);
  assert.match(functionBody("renderCurrentThread"), /taskCardsHtml\}\$\{liveOperationDock\}/);
  assert.match(functionBody("renderLiveOperation"), /renderOperationCard\(item, key, \{ status \}\)/);
  assert.match(functionBody("renderLiveOperation"), /stableOperationRenderKey\(turn, item, index\)/);
  assert.match(functionBody("renderOperationCard"), /operation-meta-line/);
  assert.match(functionBody("renderOperationCard"), /operation-detail-line/);
  assert.match(functionBody("renderOperationCard"), /operation-detail-line\$\{detail \? "" : " empty"\}/);
  assert.match(functionBody("renderOperationCard"), /detail \? escapeHtml\(detail\) : "&nbsp;"/);
  assert.match(functionBody("renderOperationCard"), /operation-title[\s\S]*operation-status/);
  assert.match(functionBody("renderOperationCard"), /operation-duration/);
  assert.match(functionBody("renderOperationCard"), /operationDurationData\(item, status\)/);
  assert.match(functionBody("updateTurnTimer"), /updateOperationDurationBadges\(\)/);
  assert.match(functionBody("operationDurationData"), /operationStartedAtMs\(item\)/);
  assert.match(functionBody("operationDurationData"), /operationCompletedAtMs\(item\)/);
  assert.match(functionBody("updateOperationDurationBadges"), /querySelectorAll\("\.operation-duration"\)/);
  assert.match(functionBody("operationDetailText"), /join\(" \\| "\)/);
  assert.match(functionBody("visibleItemsForTurn"), /if \(isOperationalItem\(item\)\) \{[\s\S]*return;/);
  assert.match(functionBody("visibleItemsForTurn"), /return visible\.filter\(Boolean\)/);
  assert.doesNotMatch(functionBody("visibleItemsForTurn"), /const showOperations/);
  assert.doesNotMatch(functionBody("visibleItemsForTurn"), /latestOperationEntry/);
  assert.doesNotMatch(functionBody("visibleItemsForTurn"), /operationEntryByKey = new Map/);
  assert.doesNotMatch(functionBody("visibleItemsForTurn"), /lastOperationEntry/);
  assert.doesNotMatch(appJs, /function trimTrailingOperationCards\(/);
  assert.match(functionBody("stableOperationRenderKey"), /operationGroupKey\(item\)/);
  assert.match(functionBody("operationGroupKey"), /item\.command/);
  assert.match(functionBody("operationGroupKey"), /operationCommandGroupText\(item\)/);
  assert.match(functionBody("operationCommandGroupText"), /operationCommandName\(item\)/);
  assert.match(functionBody("operationCommandName"), /shortPath\(stripMatchingOuterQuotes\(token\)\)/);
  assert.match(functionBody("operationSummaryLines"), /operationCommandSummary\(item\)/);
  assert.match(functionBody("operationGroupKey"), /operationRawFileNames\(item\)/);
  assert.doesNotMatch(appJs, /function latestVisibleOperationItem\(/);
  assert.doesNotMatch(appJs, /function removeOperationalItemsFromTurn\(/);
  assert.match(stylesCss, /\.live-operation-dock\s*{[\s\S]*position:\s*fixed;/);
  assert.match(stylesCss, /\.live-operation-dock\s*{[\s\S]*bottom:\s*var\(--composer-height, 92px\);/);
  assert.match(functionBody("updateLiveOperationDockMetrics"), /--live-operation-dock-reserve/);
  assert.match(stylesCss, /\.live-operation-dock \.live-operation\s*{[\s\S]*pointer-events:\s*auto;/);
  assert.match(stylesCss, /\.operation-meta-line\s*{[\s\S]*display:\s*flex;/);
  assert.match(stylesCss, /\.operation-meta-line\s*{[\s\S]*justify-content:\s*space-between;/);
  assert.match(stylesCss, /\.operation-meta-main\s*{[\s\S]*flex:\s*1 1 auto;/);
  assert.match(stylesCss, /\.operation-title\s*{[\s\S]*font-size:\s*calc\(var\(--content-small-font-size\) \* 0\.92\);/);
  assert.match(stylesCss, /\.operation-status\s*{[\s\S]*font-size:\s*calc\(var\(--content-small-font-size\) \* 0\.92\);/);
  assert.match(stylesCss, /\.operation-duration\s*{[\s\S]*font-variant-numeric:\s*tabular-nums;/);
  assert.match(stylesCss, /\.item\.live-operation\.entry-animate\s*{[\s\S]*animation:\s*none;/);
  const operationDetailLineCss = cssRuleBody(".operation-detail-line");
  assert.match(operationDetailLineCss, /height:\s*calc\(var\(--content-code-font-size\) \* 2\.68\);/);
  assert.match(operationDetailLineCss, /overflow:\s*hidden;/);
  const operationDetailCss = cssRuleBody(".operation-detail");
  assert.match(operationDetailCss, /font-size:\s*calc\(var\(--content-code-font-size\) \* 1\.06\);/);
  assert.match(operationDetailCss, /-webkit-line-clamp:\s*2;/);
  assert.match(operationDetailCss, /height:\s*100%;/);
  assert.match(operationDetailCss, /max-height:\s*100%;/);
  assert.match(operationDetailCss, /white-space:\s*normal;/);
  assert.doesNotMatch(operationDetailCss, /white-space:\s*nowrap;/);
});

test("current-turn subagent panel opens from a left swipe without a topbar button", () => {
  assert.match(indexHtml, /id="subagentPanel"/);
  assert.doesNotMatch(indexHtml, /id="subagentStatusButton"/);
  assert.match(appJs, /subagentSwipe:\s*null/);
  assert.match(appJs, /function currentSubagentItems\(/);
  assert.match(appJs, /function turnSubagentItems\(/);
  assert.match(appJs, /function beginSubagentSwipe\(/);
  assert.match(appJs, /function handleSubagentWheelSwipe\(/);
  assert.match(appJs, /addEventListener\("touchstart", beginSubagentSwipe/);
  assert.match(appJs, /addEventListener\("wheel", handleSubagentWheelSwipe/);
  assert.match(appJs, /function isHorizontalScrollableGestureTarget\(/);
  assert.match(functionBody("isHorizontalScrollableGestureTarget"), /markdown-mermaid-viewer/);
  assert.match(functionBody("isHorizontalScrollableGestureTarget"), /markdown-table-wrap/);
  assert.match(functionBody("isHorizontalScrollableGestureTarget"), /markdown-code-table-preview/);
  assert.match(functionBody("beginSubagentSwipe"), /isHorizontalScrollableGestureTarget\(event\.target\)/);
  assert.match(functionBody("handleSubagentWheelSwipe"), /isHorizontalScrollableGestureTarget\(event\.target\)/);
  assert.match(functionBody("isSubagentItem"), /collabAgentToolCall/);
  assert.match(appJs, /function activeSubagentItems\(/);
  assert.match(appJs, /function isActiveSubagentItem\(/);
  assert.match(functionBody("currentSubagentItems"), /currentLiveTurn\(\) === turn/);
  assert.match(functionBody("currentSubagentItems"), /turnSubagentItems\(turn\)/);
  assert.match(functionBody("currentSubagentItems"), /activeSubagentItems\(turn\)/);
  assert.match(functionBody("currentSubagentTurn"), /currentLiveTurn\(\)/);
  assert.match(functionBody("currentSubagentTurn"), /turnSubagentItems\(live\)\.length/);
  assert.doesNotMatch(functionBody("currentSubagentTurn"), /turns\.length - 1/);
  assert.match(functionBody("isActiveSubagentItem"), /kind === "running" \|\| kind === "queued"/);
  assert.match(appJs, /function currentSubagentStatusKind\(/);
  assert.match(functionBody("currentSubagentStatusKind"), /currentLiveTurn\(\) === turn/);
  assert.match(functionBody("currentSubagentStatusKind"), /kind === "completed" \|\| kind === "unknown"/);
  assert.match(functionBody("subagentSwipeAvailable"), /Boolean\(state\.currentThread\)/);
  assert.match(functionBody("renderSubagentPanel"), /thread-side-panel/);
  assert.match(functionBody("renderSubagentPanel"), /no-subagents/);
  assert.match(functionBody("renderSubagentPanel"), /renderSubagentStatusWindow\(\)/);
  assert.match(functionBody("renderSubagentPanel"), /renderSideChatPanel\(\)/);
  assert.match(functionBody("renderSubagentStatusWindow"), /subagent-status-window/);
  assert.match(functionBody("renderSubagentStatusWindow"), /if \(!items\.length\) return "";/);
  assert.doesNotMatch(functionBody("renderSubagentStatusWindow"), /subagent-empty/);
  assert.match(functionBody("renderSubagentStatusWindow"), /当前进行中/);
  assert.match(appJs, /function renderSideChatPanel\(/);
  assert.match(functionBody("renderSideChatPanel"), /side-chat-section/);
  assert.match(functionBody("renderSideChatPanel"), /data-side-chat-draft/);
  assert.match(functionBody("renderSideChatPanel"), /data-subagent-panel-close/);
  assert.match(functionBody("renderSideChatPanel"), /服务器保存/);
  assert.match(functionBody("renderSideChatPanel"), /side-chat-composer-row/);
  assert.match(functionBody("renderSideChatPanel"), /data-side-chat-action="tools"/);
  assert.match(functionBody("renderSideChatPanel"), /data-side-chat-action="clear"/);
  assert.match(functionBody("renderSideChatPanel"), /side-chat-clear/);
  assert.match(functionBody("renderSideChatPanel"), /renderSideChatNotice\(threadId\)/);
  assert.match(functionBody("renderSideChatPanel"), />Send</);
  assert.doesNotMatch(functionBody("renderSideChatPanel"), /side-chat-empty compact/);
  assert.match(functionBody("renderSideChatMessage"), /side-chat-message-actions/);
  assert.match(functionBody("renderSideChatMessage"), /data-side-chat-action="message-apply"/);
  assert.match(appJs, /function scheduleSideChatToBottom\(/);
  assert.match(functionBody("updateSubagentPanelUi"), /options\.scrollSideChatToBottom/);
  assert.match(functionBody("openSubagentPanelFromGesture"), /scrollSideChatToBottom: true/);
  assert.match(appJs, /function setSideChatNotice\(/);
  assert.match(appJs, /function renderSideChatNotice\(/);
  assert.match(functionBody("queueSideChatCandidate"), /setSideChatNotice\("success"/);
  assert.match(functionBody("createSideChatCandidateFromText"), /setSideChatNotice\("success"/);
  assert.match(functionBody("handleSideChatActionClick"), /openSideChatCandidate\(candidateId\)/);
  assert.match(appJs, /function loadSideChat\(/);
  assert.match(appJs, /function saveSideChatDraft\(/);
  assert.match(appJs, /function applySideChatCandidate\(/);
  assert.match(appJs, /function queueSideChatCandidate\(/);
  assert.match(appJs, /function createSideChatCandidateFromMessage\(/);
  assert.match(functionBody("scheduleSideChatDraftSave"), /saveSideChatDraft/);
  assert.doesNotMatch(functionBody("scheduleSideChatDraftSave"), /localStorage|sessionStorage|indexedDB|draftStore/);
  assert.match(stylesCss, /\.subagent-panel\s*{[\s\S]*position:\s*fixed;/);
  assert.match(stylesCss, /\.subagent-panel\s*{[\s\S]*height:\s*var\(--app-height, 100dvh\);/);
  assert.match(stylesCss, /\.subagent-panel\s*{[\s\S]*font-size:\s*var\(--content-font-size\);/);
  assert.match(stylesCss, /\.thread-side-panel/);
  assert.match(stylesCss, /\.thread-side-panel\.no-subagents\s*{[\s\S]*grid-template-rows:\s*minmax\(0, 1fr\);/);
  assert.match(stylesCss, /\.side-chat-section/);
  assert.match(stylesCss, /\.side-chat-form textarea/);
  assert.match(stylesCss, /\.side-chat-message-text,\s*\n\.side-chat-candidate-body\s*{[\s\S]*font-size:\s*var\(--content-font-size\);/);
  assert.match(stylesCss, /\.side-chat-composer-row\s*{[\s\S]*grid-template-columns:\s*44px minmax\(0, 1fr\) max-content max-content;/);
  assert.match(stylesCss, /\.side-chat-tool-button,\s*\n\.side-chat-send,\s*\n\.side-chat-clear\s*{[\s\S]*min-height:\s*44px;/);
  assert.match(stylesCss, /\.side-chat-notice\s*{[\s\S]*display:\s*flex;/);
  assert.match(stylesCss, /\.side-chat-form textarea\s*{[\s\S]*font-size:\s*var\(--composer-input-font-size\);/);
  assert.match(stylesCss, /\.subagent-status-row/);
});
