"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { test } = require("node:test");

const serverJs = fs.readFileSync(path.resolve(__dirname, "..", "server.js"), "utf8");
const appJs = fs.readFileSync(path.resolve(__dirname, "..", "public", "app.js"), "utf8");
const indexHtml = fs.readFileSync(path.resolve(__dirname, "..", "public", "index.html"), "utf8");
const stylesCss = fs.readFileSync(path.resolve(__dirname, "..", "public", "styles.css"), "utf8");
const startScript = fs.readFileSync(path.resolve(__dirname, "..", "start-codex-mobile-web.ps1"), "utf8");
const windowlessStartScript = fs.readFileSync(path.resolve(__dirname, "..", "start-codex-mobile-web-windowless.ps1"), "utf8");
const startupInstallScript = fs.readFileSync(path.resolve(__dirname, "..", "install-codex-mobile-web-startup.ps1"), "utf8");

test("server exposes Hermes plugin manifest, registration, origin, launch, session, and notification routes", () => {
  assert.match(serverJs, /"\/api\/v1\/hermes\/plugin\/manifest"/);
  assert.match(serverJs, /"\/api\/v1\/hermes\/plugin\/workspaces"/);
  assert.match(serverJs, /"\/api\/v1\/hermes\/plugin\/callbacks"/);
  assert.match(serverJs, /"\/api\/v1\/hermes\/plugin\/origins"/);
  assert.match(serverJs, /"\/api\/v1\/hermes\/plugin\/launch"/);
  assert.match(serverJs, /"\/api\/v1\/hermes\/plugin\/session"/);
  assert.match(serverJs, /"\/api\/v1\/hermes\/plugin\/notifications"/);
  assert.match(serverJs, /createHermesNotificationDelegateService/);
  assert.match(serverJs, /buildTurnCompletionDetailMessage/);
  assert.match(serverJs, /detailMessage/);
  assert.match(serverJs, /CODEX_MOBILE_HERMES_PLUGIN_NOTIFICATION_BASE_URL/);
  assert.match(serverJs, /CODEX_MOBILE_HERMES_PLUGIN_NOTIFICATION_KEY_FILE/);
  assert.match(serverJs, /notificationDelegateConfigured/);
  assert.match(serverJs, /delegateTurnCompletedNotification/);
  assert.match(serverJs, /isAccessKeyAuthorized\(req\)/);
  assert.match(serverJs, /isSessionAuthorized\(requestAuthToken\(req\)\)/);
  assert.match(serverJs, /Authorization/);
  assert.match(serverJs, /CODEX_MOBILE_HERMES_PLUGIN_BASE_URL/);
  assert.match(serverJs, /CODEX_MOBILE_PUBLIC_BASE_URL/);
  assert.match(serverJs, /CODEX_MOBILE_HERMES_PLUGIN_FRAME_ORIGINS/);
  assert.match(serverJs, /Content-Security-Policy/);
  assert.match(serverJs, /frameAncestorsHeader\(\)/);
});

test("Hermes plugin launch token is a browser-session key, not local storage login state", () => {
  assert.match(appJs, /codexPluginLaunch/);
  assert.match(appJs, /INITIAL_PLUGIN_EMBED\.embedded \? "" : localStorage\.getItem\("codexMobileKey"\)/);
  assert.match(appJs, /pluginLaunchSession: Boolean\(INITIAL_PLUGIN_LAUNCH_KEY\)/);
  assert.match(appJs, /pluginLaunchTarget: null/);
  assert.match(appJs, /queuedPluginRouteHint: INITIAL_PLUGIN_EMBED\.routeHint \|\| null/);
  assert.match(appJs, /\/api\/v1\/hermes\/plugin\/session/);
  assert.match(appJs, /state\.pluginLaunchTarget = result && result\.target/);
  assert.match(appJs, /async function applyPluginLaunchTarget\(\)/);
  assert.match(appJs, /function normalizePluginRouteHint\(value\)/);
  assert.match(appJs, /function applyUrlPluginRouteHint\(options = \{\}\)/);
  assert.match(appJs, /async function openHermesPluginRouteHint\(hint\)/);
  assert.match(appJs, /pluginRouteHintFromUrl\(window\.location\.href\)/);
  assert.match(appJs, /Notification target is unavailable/);
  assert.match(appJs, /Notification target is no longer available/);
  assert.match(appJs, /Opened notification target/);
  assert.match(appJs, /scrubPluginLaunchUrl\(\)/);
});

test("embedded plugin mode hides standalone chrome and installs navigation/windowing hooks", () => {
  assert.match(indexHtml, /params\.get\("embed"\) === "hermes"/);
  assert.match(indexHtml, /documentElement\.classList\.add\("embed-hermes"\)/);
  assert.match(indexHtml, /<script src="\/plugin-embed\.js"><\/script>/);
  assert.doesNotMatch(indexHtml, /id="embedSettingsToggle"/);
  assert.doesNotMatch(stylesCss, /html\.embed-hermes \.sidebar,\s*\nhtml\.embed-hermes #openMenu/);
  assert.match(stylesCss, /html\.embed-hermes \.sidebar\s*{[\s\S]*position:\s*fixed;[\s\S]*transform:\s*translateX\(-105%\);/);
  assert.match(stylesCss, /html\.embed-hermes \.sidebar\.open\s*{[\s\S]*transform:\s*translateX\(0\);/);
  assert.match(stylesCss, /html\.embed-hermes \.sidebar\.edge-dragging\s*{[\s\S]*translateX\(calc\(-100% \+ var\(--sidebar-edge-x, 0px\)\)\)/);
  assert.match(stylesCss, /html\.embed-hermes\.embed-hermes-primary \.sidebar\s*{[\s\S]*position:\s*relative;[\s\S]*transform:\s*none !important;/);
  assert.match(stylesCss, /html\.embed-hermes\.embed-hermes-primary \.main\s*{[\s\S]*display:\s*none;/);
  assert.match(stylesCss, /html\.embed-hermes\.embed-hermes-primary #closeMenu\s*{[\s\S]*display:\s*none !important;/);
  assert.match(stylesCss, /html\.embed-hermes \.app[\s\S]*grid-template-columns:\s*minmax\(0, 1fr\)/);
  assert.match(appJs, /codex-mobile\.plugin\.navigation|pluginEmbedApi\.navigationMessage/);
  assert.match(appJs, /codex-mobile\.plugin\.back_result|postPluginBackResult|pluginEmbedApi\.postBackResult/);
  assert.match(appJs, /hermes\.plugin\.back|pluginEmbedApi\.isBackMessage/);
  assert.doesNotMatch(appJs, /openEmbedSettingsPanel/);
  assert.doesNotMatch(appJs, /function isPluginRootSwipeTarget/);
  assert.match(appJs, /function isHermesPluginPrimaryPage\(\)/);
  assert.match(appJs, /function showHermesPluginPrimaryPage\(\)/);
  assert.match(appJs, /function beginSidebarEdgeSwipe\(event\) \{\s*if \(!isMobileViewport\(\) \|\| isHermesEmbedMode\(\)/);
  assert.match(appJs, /else if \(state\.currentThreadId \|\| state\.newThreadDraft \|\| state\.selectedCwd\) \{[\s\S]*handled = showHermesPluginPrimaryPage\(\);/);
  assert.doesNotMatch(appJs, /host_back_from_settings/);
  assert.doesNotMatch(appJs, /host_back_from_sidebar/);
  assert.doesNotMatch(appJs, /else if \(\$\("themeSettingsPanel"\)[\s\S]{0,180}closeSidebarMenu\(\);[\s\S]{0,80}handled = true;/);
  assert.doesNotMatch(appJs, /function returnPluginRootStep/);
  assert.doesNotMatch(appJs, /function openPluginNavigationSurface/);
  assert.match(appJs, /addEventListener\("touchstart", beginSidebarEdgeSwipe, \{ passive: true \}\)/);
  assert.match(appJs, /function pushBrowserAvailable\(\) \{\s*if \(isHermesEmbedMode\(\)\) return false;/);
  assert.match(appJs, /function showCompletionAlert\(threadId, threadName\) \{\s*if \(isHermesEmbedMode\(\)\) return;/);
  assert.match(appJs, /installPluginWindowingGuards\(\)/);
  assert.match(appJs, /window\.open = function guardedPluginOpen/);
  assert.match(appJs, /function requestHermesPluginRefresh\(reason, options = \{\}\)/);
  assert.match(appJs, /if \(!isHermesEmbedMode\(\) \|\| !pluginEmbedApi\.postRefreshRequired\) return false;/);
  assert.match(appJs, /pluginRefreshPendingNotice:\s*""/);
  assert.match(appJs, /function pluginRefreshPendingMessage\(reason\)/);
  assert.match(appJs, /state\.pluginRefreshPendingNotice = pluginRefreshPendingMessage\(normalizedReason\);/);
  assert.match(appJs, /Refreshing plugin page from Hermes Mobile\.\.\./);
  assert.match(appJs, /Refreshing plugin page for a new Mobile Web build\.\.\./);
  assert.match(appJs, /function renderPluginRefreshPendingNotice\(previousKeys = new Set\(\)\)/);
  assert.match(appJs, /plugin-refresh-pending/);
  assert.match(stylesCss, /\.plugin-refresh-pending/);
  assert.match(appJs, /pluginEmbedApi\.postRefreshRequired\(window\.parent, \{/);
  assert.match(appJs, /requestHermesPluginRefresh\("server_build_changed"/);
  assert.match(appJs, /requestHermesPluginRefresh\("auth_state_changed"/);
  assert.match(appJs, /function showPluginEmbedRecovering\(message = ""\)/);
  assert.match(appJs, /showPluginEmbedRecovering\("Refreshing Codex Mobile plugin session\.\.\."\)/);
  assert.match(appJs, /showPluginEmbedRecovering\("Refreshing Codex Mobile plugin launch\.\.\."\)/);
  assert.match(appJs, /targetOrigin:\s*targetOrigin \|\| "\*"/);
  assert.match(appJs, /const hermesOrigin = normalizePluginParentOrigin\(result && result\.hermes_origin\)/);
  assert.match(appJs, /state\.pluginParentOrigin = hermesOrigin/);
  assert.match(appJs, /if \(isHermesEmbedMode\(\)\) \{\s*state\.pageRefreshBuildId = nextBuildId;[\s\S]*requestHermesPluginRefresh\("server_build_changed", \{ force: true \}\);[\s\S]*return;/);
});

test("Windows startup scripts can persist HTTPS Hermes plugin deployment settings", () => {
  assert.match(startScript, /\[string\]\$HermesPluginBaseUrl/);
  assert.match(startScript, /\$env:CODEX_MOBILE_HERMES_PLUGIN_BASE_URL = \$HermesPluginBaseUrl/);
  assert.match(startScript, /\[string\]\$PublicBaseUrl/);
  assert.match(startScript, /\$env:CODEX_MOBILE_PUBLIC_BASE_URL = \$PublicBaseUrl/);
  assert.match(startScript, /\[string\]\$HermesPluginFrameOrigins/);
  assert.match(startScript, /\$env:CODEX_MOBILE_HERMES_PLUGIN_FRAME_ORIGINS = \$HermesPluginFrameOrigins/);
  assert.match(startScript, /\[string\]\$HermesPluginNotificationBaseUrl/);
  assert.match(startScript, /\$env:CODEX_MOBILE_HERMES_PLUGIN_NOTIFICATION_BASE_URL = \$HermesPluginNotificationBaseUrl/);
  assert.match(startScript, /\[string\]\$HermesPluginNotificationKeyFile/);
  assert.match(startScript, /\$env:CODEX_MOBILE_HERMES_PLUGIN_NOTIFICATION_KEY_FILE = \$HermesPluginNotificationKeyFile/);

  assert.match(windowlessStartScript, /\[string\]\$HermesPluginBaseUrl/);
  assert.match(windowlessStartScript, /\$parameters\.HermesPluginBaseUrl = \$HermesPluginBaseUrl/);
  assert.match(windowlessStartScript, /\$parameters\.HermesPluginFrameOrigins = \$HermesPluginFrameOrigins/);
  assert.match(windowlessStartScript, /\$parameters\.HermesPluginNotificationBaseUrl = \$HermesPluginNotificationBaseUrl/);
  assert.match(windowlessStartScript, /\$parameters\.HermesPluginNotificationKeyFile = \$HermesPluginNotificationKeyFile/);

  assert.match(startupInstallScript, /\[string\]\$HermesPluginBaseUrl/);
  assert.match(startupInstallScript, /"-HermesPluginBaseUrl", \(Quote-TaskArgument \$HermesPluginBaseUrl\)/);
  assert.match(startupInstallScript, /"-HermesPluginFrameOrigins", \(Quote-TaskArgument \$HermesPluginFrameOrigins\)/);
  assert.match(startupInstallScript, /"-HermesPluginNotificationBaseUrl", \(Quote-TaskArgument \$HermesPluginNotificationBaseUrl\)/);
  assert.match(startupInstallScript, /"-HermesPluginNotificationKeyFile", \(Quote-TaskArgument \$HermesPluginNotificationKeyFile\)/);
});
