"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { test } = require("node:test");

const indexHtml = fs.readFileSync(path.resolve(__dirname, "..", "public", "index.html"), "utf8");
const appJs = fs.readFileSync(path.resolve(__dirname, "..", "public", "app.js"), "utf8");
const stylesCss = fs.readFileSync(path.resolve(__dirname, "..", "public", "styles.css"), "utf8");
const swJs = fs.readFileSync(path.resolve(__dirname, "..", "public", "sw.js"), "utf8");
const threadDetailMergeStateJs = fs.readFileSync(path.resolve(__dirname, "..", "public", "thread-detail-merge-state.js"), "utf8");
const viewportMetricsJs = fs.readFileSync(path.resolve(__dirname, "..", "public", "viewport-metrics.js"), "utf8");
const platformPointer = fs.readFileSync(path.resolve(__dirname, "..", "docs", "HOME_AI_PLATFORM_CONTRACT.md"), "utf8");

function functionBody(name) {
  const start = appJs.indexOf(`function ${name}(`);
  assert.notEqual(start, -1, `missing function ${name}`);
  const bodyStart = appJs.indexOf(") {", start) + 2;
  assert.notEqual(bodyStart, 1, `missing function body ${name}`);
  let depth = 0;
  for (let index = bodyStart; index < appJs.length; index += 1) {
    const char = appJs[index];
    if (char === "{") depth += 1;
    if (char === "}") depth -= 1;
    if (depth === 0) return appJs.slice(bodyStart + 1, index);
  }
  throw new Error(`could not parse function ${name}`);
}

test("mobile viewport and early guards disable page zoom", () => {
  assert.match(indexHtml, /name="viewport" content="[^"]*maximum-scale=1/);
  assert.match(indexHtml, /name="viewport" content="[^"]*minimum-scale=1/);
  assert.match(indexHtml, /name="viewport" content="[^"]*user-scalable=no/);
  assert.match(indexHtml, /addEventListener\("gesturestart", preventZoom, \{ passive: false \}\)/);
  assert.match(indexHtml, /addEventListener\("gesturechange", preventZoom, \{ passive: false \}\)/);
  assert.match(indexHtml, /addEventListener\("dblclick", preventZoom, \{ passive: false \}\)/);
  assert.match(indexHtml, /lastTouchEndAt < 320/);
  assert.match(indexHtml, /<script src="\/viewport-metrics\.js"><\/script>/);
  assert.match(indexHtml, /<script src="\/conversation-scroll\.js"><\/script>/);
  assert.match(indexHtml, /<script src="\/image-compressor\.js"><\/script>/);
  assert.match(indexHtml, /<script src="\/plugin-embed\.js"><\/script>/);
  assert.match(appJs, /const viewportMetrics = window\.CodexViewportMetrics/);
  assert.match(appJs, /viewportMetrics\.measureViewport\(\{/);
  assert.match(viewportMetricsJs, /const keyboardShrunk = Boolean\(keyboardInputActive && \(keyboardCandidate \|\| offsetKeyboardShifted \|\| scrollKeyboardShifted \|\| hostKeyboardVisible\)\)/);
  assert.match(viewportMetricsJs, /hostKeyboardBottomInset/);
  assert.match(viewportMetricsJs, /hostKeyboardVisible/);
  assert.match(viewportMetricsJs, /hostViewportHeight/);
  assert.match(viewportMetricsJs, /offsetKeyboardShifted/);
  assert.match(viewportMetricsJs, /scrollKeyboardShifted/);
  assert.match(appJs, /hostViewportHeight:\s*embedded && hostViewport && hostViewport\.viewport \? hostViewport\.viewport\.height : 0/);
  assert.match(appJs, /scrollTop:\s*embedded \? Math\.max\(/);
  assert.match(appJs, /function resetMobileKeyboardWindowScroll\(\)/);
  assert.match(appJs, /if \(isHermesEmbedMode\(\) \|\| !isKeyboardEditableElement\(document\.activeElement\)\) return;/);
  assert.match(appJs, /if \(typeof window\.scrollTo === "function"\) window\.scrollTo\(0, 0\);/);
  assert.match(appJs, /if \(viewport\.keyboardShrunk\) \{[\s\S]*--app-height/);
  assert.match(appJs, /--app-top/);
  assert.match(appJs, /document\.documentElement\.style\.removeProperty\("--app-height"\)/);
  assert.match(appJs, /document\.documentElement\.classList\.toggle\("keyboard-open", viewport\.keyboardShrunk\)/);
  assert.match(appJs, /pluginHostViewport: null/);
  assert.match(appJs, /function normalizeHermesPluginViewportRect\(rect\)/);
  assert.match(appJs, /function normalizeHermesPluginViewportMessage\(data\)/);
  assert.match(appJs, /data\.type !== "hermes\.plugin\.viewport"/);
  assert.match(appJs, /iframe:\s*normalizeHermesPluginViewportRect\(data\.iframe\)/);
  assert.match(appJs, /host:\s*normalizeHermesPluginViewportRect\(data\.host\)/);
  assert.match(appJs, /handleHermesPluginViewportMessage\(event && event\.data\)/);
  assert.match(appJs, /state\.pluginHostViewport = normalized;[\s\S]*syncThreadDetailLayoutState\(\);/);
  assert.match(appJs, /function isHermesKeyboardInputActive\(\) \{[\s\S]*isHermesEmbedMode\(\)[\s\S]*isKeyboardEditableElement\(document\.activeElement\)/);
  assert.match(appJs, /window\.visualViewport\.addEventListener\("resize", \(\) => \{[\s\S]*if \(!isHermesKeyboardInputActive\(\)\) \{[\s\S]*scheduleVisualRecovery\("visual-viewport"/);
  assert.match(appJs, /window\.visualViewport\.addEventListener\("scroll", \(\) => \{[\s\S]*if \(!isHermesKeyboardInputActive\(\)\) \{[\s\S]*scheduleVisualRecovery\("visual-viewport-scroll"/);
  assert.match(appJs, /HEAVY_VISUAL_RECOVERY_MIN_INTERVAL_MS = 4000/);
  assert.match(appJs, /function visualRecoveryReasonAllowsHeavy\(reason = ""\)/);
  assert.match(appJs, /\^\(focus\|focusin\|focusout\|resize\|visual-viewport\|visual-viewport-scroll\|window-blur\)\$/);
  assert.match(appJs, /function shouldRunHeavyVisualRecovery\(reason = "resume"\)/);
  assert.match(appJs, /now - state\.lastHeavyVisualRecoveryAt < HEAVY_VISUAL_RECOVERY_MIN_INTERVAL_MS/);
  assert.match(appJs, /forceVisualRecovery\(reason, \{ heavy: index === 0 && allowHeavyRecovery \}\)/);
  assert.match(appJs, /forceVisualRecovery\(reason, \{ heavy: false \}\);[\s\S]*updateComposerHeightVar\(\);/);
  assert.doesNotMatch(appJs, /0\.01px/);
  assert.match(stylesCss, /html,\s*\nbody\s*{[\s\S]*touch-action:\s*pan-x pan-y;/);
  assert.match(stylesCss, /html\s*{[\s\S]*height:\s*-webkit-fill-available;/);
  assert.match(stylesCss, /body\s*{[\s\S]*min-height:\s*-webkit-fill-available;/);
  assert.match(stylesCss, /html\.embed-hermes \.app\s*{[\s\S]*height:\s*var\(--app-height, 100dvh\);/);
  assert.match(stylesCss, /html\.embed-hermes \.app\s*{[\s\S]*min-height:\s*0;/);
  assert.match(stylesCss, /html\.embed-hermes \.app\s*{[\s\S]*transform:\s*translateY\(var\(--app-top, 0px\)\);/);
  assert.match(stylesCss, /\.app\.resume-repaint\s*{[\s\S]*transform:\s*translateY\(var\(--app-top, 0px\)\) translateZ\(0\);/);
  assert.match(stylesCss, /--host-top-safe-area:\s*0px;/);
  assert.match(stylesCss, /html\.embed-hermes \.topbar\s*{[\s\S]*padding-top:\s*calc\(6px \+ max\(env\(safe-area-inset-top, 0px\), var\(--host-top-safe-area, 0px\)\)\);[\s\S]*padding-bottom:\s*6px;/);
  assert.match(appJs, /hostTopSafeArea:\s*boundedViewportNumber\(topSafeArea, 512\)/);
  assert.match(appJs, /--host-top-safe-area/);
  assert.match(stylesCss, /html\.embed-hermes \.composer\s*{[\s\S]*padding-bottom:\s*max\(12px, var\(--host-bottom-safe-area, 0px\)\);/);
  assert.match(stylesCss, /html\.embed-hermes\.keyboard-open \.composer\s*{[\s\S]*padding-bottom:\s*max\(10px, var\(--host-bottom-safe-area, 0px\)\);/);
  assert.match(stylesCss, /html\.embed-hermes \.main \.version-actions/);
  assert.match(indexHtml, /id="continuationDialog"/);
  assert.match(appJs, /function openContinuationDialog\(/);
  assert.match(appJs, /function continuationDialogOpen\(/);
  assert.match(appJs, /function closeContinuationDialog\(/);
  assert.match(stylesCss, /\.continuation-dialog/);
  assert.match(stylesCss, /html\.keyboard-open \.composer\s*{[\s\S]*padding-bottom:\s*12px;/);
  assert.match(stylesCss, /@media \(max-width: 760px\)[\s\S]*\.composer\s*{[\s\S]*gap:\s*6px;[\s\S]*padding:\s*7px 12px clamp\(8px, calc\(env\(safe-area-inset-bottom, 0px\) - 88px\), 52px\);/);
  assert.match(stylesCss, /@media \(max-width: 760px\)[\s\S]*html\.embed-hermes \.composer\s*{[\s\S]*padding-bottom:\s*max\(12px, var\(--host-bottom-safe-area, 0px\)\);/);
  assert.match(stylesCss, /@media \(max-width: 760px\)[\s\S]*html\.embed-hermes\.keyboard-open \.composer\s*{[\s\S]*padding-bottom:\s*max\(8px, var\(--host-bottom-safe-area, 0px\)\);/);
  assert.match(stylesCss, /@media \(max-width: 760px\)[\s\S]*html\.keyboard-open \.composer\s*{[\s\S]*padding-bottom:\s*7px;/);
  assert.match(platformPointer, /embedded-plugin-keyboard-composer/);
  assert.match(platformPointer, /--plugin-thread-id <thread-id>/);
  assert.match(platformPointer, /development visual check passes/);
});

test("Android composer stale focus is released before the native tap", () => {
  const prepareBody = functionBody("prepareMessageInputForNativeGesture");
  const recoverBody = functionBody("recoverMessageInputKeyboardFromGesture");
  const shouldRecoverBody = functionBody("shouldRecoverMessageInputKeyboard");
  const releaseBody = functionBody("releaseStaleAndroidMessageInputFocusBeforeNativeTap");
  assert.match(prepareBody, /if \(!input \|\| !isAndroidBrowser\(\)\) return;/);
  assert.match(prepareBody, /setMessageInputDisabled\(false\)/);
  assert.match(prepareBody, /releaseStaleAndroidMessageInputFocusBeforeNativeTap\(input\)/);
  assert.doesNotMatch(prepareBody, /focusMessageInput|preventDefault/);
  assert.match(releaseBody, /messageInputKeyboardVisible\(\)/);
  assert.match(releaseBody, /input\.blur\(\)/);
  assert.match(shouldRecoverBody, /if \(!isAndroidBrowser\(\) && !isHermesEmbedMode\(\)\) return false;/);
  assert.doesNotMatch(shouldRecoverBody, /if \(isAndroidBrowser\(\)\) return false;/);
  assert.match(recoverBody, /if \(isAndroidBrowser\(\)\) return false;/);
  assert.match(recoverBody, /resetActiveFocus: true/);
  assert.match(recoverBody, /allowAndroidActiveFocusReset: true/);
});

test("composer sizing avoids one-pixel layout churn while typing and streaming", () => {
  assert.match(appJs, /composerHeightPx:\s*0/);
  assert.match(appJs, /function updateComposerHeightVar\(options = \{\}\)/);
  assert.match(appJs, /stablePixelChanged\(previousPx, nextPx\)/);
  assert.match(appJs, /document\.documentElement\.style\.setProperty\("--composer-height", `\$\{nextPx\}px`\)/);
  assert.match(appJs, /function autoSizeMessageInput\(el, options = \{\}\)/);
  assert.match(appJs, /nextTextLength < previousTextLength/);
  assert.match(appJs, /autoSizeMessageInput\(event\.target\);/);
  assert.match(appJs, /updateMessageInputOverflow\(el, nextHeight\)/);
  assert.match(stylesCss, /\.message-input\s*{[\s\S]*height:\s*44px;[\s\S]*overflow-y:\s*hidden;/);
});

test("turn timer preserves elapsed digits on narrow embedded viewports", () => {
  assert.match(stylesCss, /\.turn-timer\s*{[\s\S]*width:\s*auto;/);
  assert.match(stylesCss, /\.turn-timer\s*{[\s\S]*max-width:\s*min\(58vw, 320px\);/);
  assert.match(stylesCss, /\.turn-timer\.visible\s*{[\s\S]*display:\s*inline-flex;/);
  assert.match(stylesCss, /\.turn-timer-time\s*{[\s\S]*flex:\s*0 0 auto;/);
  assert.match(stylesCss, /\.turn-timer-time\s*{[\s\S]*min-width:\s*12\.75em;/);
  assert.match(stylesCss, /\.turn-timer-time\s*{[\s\S]*overflow:\s*visible;/);
  assert.match(stylesCss, /\.turn-timer-detail\s*{[\s\S]*flex:\s*1 1 auto;/);
  assert.match(stylesCss, /\.turn-timer-detail\s*{[\s\S]*text-overflow:\s*ellipsis;/);
  assert.doesNotMatch(stylesCss, /\.turn-timer-time\s*{[\s\S]*flex:\s*0 0 104px;/);
});

test("public app shell cache advances after local stream item insertion", () => {
  assert.match(swJs, /codex-mobile-shell-v506/);
  assert.match(appJs, /CLIENT_BUILD_ID = "0\.1\.11\|codex-mobile-shell-v506"/);
  assert.match(swJs, /"\/home-ai-diagnostic-reporting\.js"/);
  assert.match(appJs, /"\/home-ai-diagnostic-reporting\.js"/);
  assert.match(swJs, /"\/thread-diagnostic-events\.js"/);
  assert.match(appJs, /"\/thread-diagnostic-events\.js"/);
  assert.match(swJs, /"\/thread-status-hints\.js"/);
  assert.match(swJs, /"\/thread-performance-metrics\.js"/);
  assert.match(swJs, /"\/live-operation-dock-state\.js"/);
  assert.match(swJs, /"\/thread-detail-state\.js"/);
  assert.match(swJs, /"\/thread-detail-render-plan\.js"/);
  assert.match(swJs, /"\/thread-detail-merge-state\.js"/);
  assert.match(swJs, /"\/thread-detail-patch-plan\.js"/);
  assert.match(swJs, /"\/thread-detail-dom-patch\.js"/);
  assert.match(swJs, /"\/thread-detail-actions\.js"/);
  assert.match(swJs, /"\/thread-tile-actions\.js"/);
  assert.match(swJs, /"\/thread-tile-state\.js"/);
  assert.match(swJs, /"\/thread-tile-layout\.js"/);
  assert.match(stylesCss, /\.subagent-panel\s*{[\s\S]*position:\s*fixed;[\s\S]*height:\s*var\(--app-height, 100dvh\);/);
  assert.match(stylesCss, /\.thread-side-panel\s*{[\s\S]*grid-template-rows:\s*minmax\(92px, 0\.42fr\) minmax\(224px, 1fr\);/);
  assert.match(stylesCss, /\.thread-side-panel\.no-subagents\s*{[\s\S]*grid-template-rows:\s*minmax\(0, 1fr\);/);
  assert.match(stylesCss, /\.side-chat-scroll\s*{[\s\S]*overflow:\s*auto;/);
  assert.match(stylesCss, /\.side-chat-section\s*{[\s\S]*height:\s*100%;/);
  assert.match(stylesCss, /\.side-chat-header\s*{[\s\S]*grid-template-columns:\s*minmax\(0, 1fr\) auto auto auto;/);
  assert.match(stylesCss, /\.side-chat-composer-row\s*{[\s\S]*grid-template-columns:\s*44px minmax\(0, 1fr\) max-content;/);
  assert.match(stylesCss, /@media \(max-width: 760px\)[\s\S]*\.composer\s*{[\s\S]*grid-template-columns:\s*52px minmax\(0, 1fr\) max-content;/);
  assert.match(stylesCss, /@media \(max-width: 760px\)[\s\S]*\.attachment-picker-cell\s*{[\s\S]*width:\s*52px;[\s\S]*height:\s*44px;/);
  assert.match(stylesCss, /\.side-chat-header-clear\s*{[\s\S]*justify-self:\s*end;/);
  assert.match(stylesCss, /\.side-chat-form textarea\s*{[\s\S]*min-height:\s*44px;[\s\S]*max-height:\s*160px;[\s\S]*overflow-y:\s*hidden;/);
  assert.match(stylesCss, /\.subagent-panel\s*{[\s\S]*z-index:\s*40;/);
  assert.match(stylesCss, /html\.keyboard-open \.subagent-panel\s*{[\s\S]*height:\s*var\(--app-height, 100dvh\);[\s\S]*max-height:\s*none;/);
  assert.match(stylesCss, /html\.keyboard-open \.thread-side-panel\s*{[\s\S]*grid-template-rows:\s*minmax\(44px, 0\.18fr\) minmax\(0, 1fr\);/);
  assert.match(stylesCss, /html\.keyboard-open \.thread-side-panel\.no-subagents\s*{[\s\S]*grid-template-rows:\s*minmax\(0, 1fr\);/);
  assert.match(stylesCss, /html\.keyboard-open \.side-chat-form textarea\s*{[\s\S]*min-height:\s*44px;[\s\S]*max-height:\s*min\(14vh, 84px\);/);
  assert.match(appJs, /function ensureSideChatDraftVisible\(/);
  assert.match(appJs, /function autoSizeSideChatDraftTextarea\(/);
  assert.match(appJs, /autoSizeSideChatDraftTextarea\(textarea\)/);
  assert.match(appJs, /requestAnimationFrame\(ensureSideChatDraftVisible\)/);
  assert.match(appJs, /function scheduleSideChatPoll\(/);
  assert.match(appJs, /侧聊正在回复/);
  assert.match(appJs, /function flushSideChatDraftNow\(/);
  assert.match(appJs, /loadSideChat\(threadId, \{ silent: true \}\)\.catch\(showError\)/);
  assert.match(appJs, /function serverBuildIdFromConfig\(config\) \{\s*return String\(config && \(config\.clientBuildId \|\| config\.shellCacheName \|\| config\.buildId\) \|\| ""\)\.trim\(\);/);
  assert.doesNotMatch(appJs, /function serverBuildIdFromConfig\(config\) \{\s*return String\(config && \(config\.clientBuildId \|\| config\.shellCacheName \|\| config\.buildId \|\| config\.version\)/);
  assert.match(appJs, /startupThreadOpenPending: false/);
  assert.match(indexHtml, /id="pluginStartupLoading"/);
  assert.match(indexHtml, /data-plugin-startup-title>正在加载 Codex\.\.\.</);
  assert.match(appJs, /pluginStartupLoading: Boolean\(INITIAL_PLUGIN_EMBED\.embedded\)/);
  assert.match(appJs, /function showPluginStartupLoading\(message = ""\)/);
  assert.match(appJs, /function hidePluginStartupLoading\(\)/);
  assert.match(appJs, /if \(isHermesEmbedMode\(\)\) showPluginStartupLoading\(\);/);
  assert.match(appJs, /hidePluginStartupLoading\(\);[\s\S]*}\s*\n\s*function threadIdFromUrlValue/);
  assert.match(stylesCss, /html\.embed-hermes\.plugin-startup-loading \.app/);
  assert.match(stylesCss, /\.plugin-startup-loading\s*{[\s\S]*position:\s*fixed;[\s\S]*place-items:\s*center;/);
  assert.doesNotMatch(appJs, /thread-card-token-badge/);
  assert.doesNotMatch(stylesCss, /thread-card-token-badge/);
  assert.match(appJs, /const savedThreadId = isHermesEmbedMode\(\) \? "" : \(localStorage\.getItem\(STORAGE_THREAD_ID\) \|\| ""\);/);
  assert.match(appJs, /function hasStartupThreadOpenIntent\(\)/);
  assert.match(appJs, /postClientEvent\("startup_stage"/);
  assert.match(appJs, /postPerformanceEvent\("shell_loaded"/);
  assert.match(appJs, /postPerformanceEvent\("thread_list_rendered"/);
  assert.match(appJs, /const listPerformance = threadPerformanceMetrics\.threadListEventFields\(result\);/);
  assert.match(appJs, /serverTimings: listPerformance\.serverTimings/);
  assert.match(appJs, /performancePhase: listPerformance\.performancePhase/);
  assert.match(functionBody("loadThread"), /threadPerformanceMetrics\.threadDetailFirstPaintEventFields\(state\.currentThread, \{/);
  assert.match(functionBody("loadThread"), /threadPerformanceMetrics\.threadDetailFirstPaintEventFields\(result\.thread, \{/);
  assert.match(appJs, /postPerformanceEvent\("thread_detail_first_paint"/);
  assert.match(appJs, /postPerformanceEvent\("conversation_render_ms"/);
  assert.match(appJs, /postPerformanceEvent\("github_cards_hydrate_ms"/);
  assert.match(appJs, /postPerformanceEvent\("mermaid_hydrate_ms"/);
  assert.match(appJs, /postPerformanceEvent\("thread_refresh_ms"/);
  assert.match(appJs, /state\.startupThreadOpenPending = hasStartupThreadOpenIntent\(\);[\s\S]*early_opening_rendered/);
  assert.match(appJs, /async function fetchPublicConfigWithRetry\(startedAt\)/);
  assert.match(appJs, /PUBLIC_CONFIG_RETRY_DELAYS_MS = \[0, 300, 1200\]/);
  assert.match(appJs, /fetchJsonWithTimeout\("\/api\/public-config"/);
  assert.match(appJs, /postStartupStage\("public_config_done"/);
  assert.match(appJs, /postStartupStage\("public_config_failed"/);
  assert.match(appJs, /requestHermesPluginRefresh\("public_config_failed", \{ force: true \}\)/);
  assert.match(appJs, /state\.startupThreadOpenPending = Boolean\(startupThreadId \|\| savedThreadId \|\| \(startupPluginRouteHint && startupPluginRouteHint\.threadId\)\);/);
  assert.match(appJs, /const earlyRestorePromise = savedThreadId && !startupThreadId[\s\S]*loadThread\(savedThreadId, \{ source: "restore-startup" \}\)/);
  assert.match(appJs, /const status = await api\("\/api\/status"\)\.catch/);
  assert.match(appJs, /const workspacesStartedAt = nowPerfMs\(\);\s*\n\s*await loadWorkspaces\(\);/);
  assert.match(appJs, /await loadWorkspaces\(\);[\s\S]*await loadThreads\(\{ silent: startupThreadOpenPending, deferFallback: true \}\);/);
  assert.match(appJs, /postStartupStage\("status_done"/);
  assert.match(appJs, /postStartupStage\("threads_done"/);
  assert.match(appJs, /startupInProgress: false/);
  assert.match(appJs, /mobile_resume_skipped_startup/);
  assert.match(appJs, /await loadThreads\(\{ silent: startupThreadOpenPending, deferFallback: true \}\);/);
  assert.match(appJs, /function renderStartupThreadOpening\(\)/);
  assert.match(appJs, /Opening thread\.\.\./);
  assert.match(appJs, /if \(state\.startupThreadOpenPending\) \{[\s\S]*renderStartupThreadOpening\(\);[\s\S]*return;/);
  assert.match(appJs, /function showPluginEmbedRecovering\(message = ""\)/);
  assert.match(appJs, /Refreshing Codex Mobile plugin session\.\.\./);
  assert.match(appJs, /Refreshing Codex Mobile plugin launch\.\.\./);
  assert.match(appJs, /Refreshing plugin page from Hermes Mobile\.\.\./);
  assert.match(appJs, /state\.pluginRefreshPendingTimer = window\.setTimeout\(\(\) => \{/);
  assert.match(appJs, /function clearPluginRefreshPendingNotice\(\)/);
  assert.match(appJs, /Generating cross-thread task card draft\.\.\./);
  assert.match(stylesCss, /\.plugin-refresh-pending/);
  assert.match(stylesCss, /\.approval-details/);
  assert.match(stylesCss, /\.approval-summary-line/);
  assert.match(appJs, /if \(threadId === state\.currentThreadId && state\.currentThread && !state\.currentThread\.mobileLoadError\) \{/);
  assert.match(appJs, /scheduleCurrentThreadRefresh\(250\);[\s\S]*openExternalThreadSelection\(threadId\)\.catch\(showError\);/);
  assert.match(appJs, /function currentThreadNeedsForegroundRefresh\(\)/);
  assert.match(appJs, /function currentThreadListRowChanged\(\)/);
  assert.match(appJs, /threadUpdatedAtMs\(row\)/);
  assert.match(appJs, /mobile_resume_thread_refresh_scheduled/);
  assert.match(appJs, /function isTransientResumeError\(err\)/);
  assert.match(appJs, /function scheduleTransientResumeRetry\(reason, delay = 1200\)/);
  assert.match(appJs, /async function resumeMobileSession\(reason = "resume"\)[\s\S]*transient: isTransientResumeError\(err\)/);
  assert.match(appJs, /async function resumeMobileSession\(reason = "resume"\)[\s\S]*if \(isTransientResumeError\(err\)\) \{[\s\S]*scheduleTransientResumeRetry\(reason\);[\s\S]*return;/);
  assert.match(appJs, /function autoTurnRecoveryCandidate\(\)/);
  assert.match(appJs, /function autoTurnRecoveryCandidates\(\)/);
  assert.match(appJs, /function autoTurnRecoveryCandidates\(\)[\s\S]*for \(const thread of state\.restartAutoRecoverThreads \|\| \[\]\)/);
  assert.doesNotMatch(appJs, /function autoTurnRecoveryCandidates\(\)[\s\S]*for \(const thread of state\.threads \|\| \[\]\)[\s\S]*return Array\.from\(byId\.values\(\)\);/);
  assert.doesNotMatch(appJs, /function autoTurnRecoveryCandidates\(\)[\s\S]*const current = autoTurnRecoveryCandidate\(\)[\s\S]*return Array\.from\(byId\.values\(\)\);/);
  assert.match(appJs, /STORAGE_RESTART_AUTO_RECOVER_THREADS/);
  assert.match(appJs, /async function maybeAutoRecoverTurnAfterReconnect\(status, reason = "reconnect"\)/);
  assert.match(appJs, /\/auto-recover/);
  assert.match(appJs, /const recovered = wasUnavailable && status && status\.ready;/);
  assert.match(appJs, /maybeAutoRecoverTurnAfterReconnect\(payload\.status, "app-server-reconnect"\)/);
  assert.match(appJs, /if \(state\.currentThreadId && state\.currentThread && !state\.currentThread\.mobileLoading && !state\.currentThread\.mobileLoadError\) \{/);
  assert.match(appJs, /return shouldPollCurrentThread\(\) \|\| currentThreadListRowChanged\(\);/);
  assert.match(appJs, /const foregroundRefresh = currentThreadNeedsForegroundRefresh\(\);[\s\S]*mobile_resume_thread_refresh_scheduled[\s\S]*if \(foregroundRefresh\) scheduleCurrentThreadRefresh\(250, "resume"\);[\s\S]*else await refreshCurrentThread\(\{ source: "resume" \}\);[\s\S]*else if \(state\.currentThreadId\) \{[\s\S]*await refreshCurrentThread\(\{ source: "resume" \}\);[\s\S]*else \{[\s\S]*await restoreThreadSelection\(\);/);
  assert.match(appJs, /async function restoreThreadSelection\(\) \{[\s\S]*if \(isHermesEmbedMode\(\)\) \{[\s\S]*showHermesPluginPrimaryPage\(\);[\s\S]*return;/);
  assert.match(appJs, /renderCurrentThread\(\{ stickToBottom: true \}\);\s*\n\s*publishPluginNavigationState\(\{ force: true \}\);\s*\n\s*updateComposerControls\(\);/);
  assert.doesNotMatch(appJs, /function shouldOpenLargeThreadHistoryAtTop/);
  assert.doesNotMatch(appJs, /function threadOpenRenderOptions/);
  assert.doesNotMatch(appJs, /scrollConversationToTop/);
  assert.doesNotMatch(appJs, /scrollToTop/);
  assert.match(appJs, /const explicitNoStickToBottom = options\.stickToBottom === false \|\| Boolean\(options\.scrollToTurnReceiptStart\);/);
  assert.match(appJs, /renderCurrentThread\(\{ stickToBottom: true \}\);\s*\n\s*const conversationRenderMs = roundedDurationMs\(conversationRenderStartedAt\);\s*\n\s*if \(replacedTilePaneForThreadListOpen\) \{[\s\S]*restoreDraftForCurrentTarget\(\{ resetRuntimeWhenMissingDraft: true \}\);[\s\S]*updateComposerControls\(\);[\s\S]*\}\s*\n\s*if \(isMenuOverlayMode\(\)\) closeSidebarMenu\(\);/);
  assert.match(appJs, /renderCurrentThread\(\{ stickToBottom: true \}\);\s*\n\s*const conversationRenderMs = roundedDurationMs\(conversationRenderStartedAt\);\s*\n\s*const postRenderStartedAt = nowPerfMs\(\);\s*\n\s*publishPluginNavigationState\(\{ force: true \}\);\s*\n\s*restoreConnectionState\(\);/);
  assert.match(appJs, /const PLUGIN_EMBED_BACK_EDGE_SWIPE_PX = 44/);
  assert.match(appJs, /function installHermesPluginBackSwipeGuard\(\)/);
  assert.match(appJs, /pluginEmbedApi\.navigationMessage\(state, pluginNavigationUiState\(\)\)/);
  assert.doesNotMatch(appJs, /function pluginEmbedBackSwipeShouldExitHost\(\)/);
  assert.match(appJs, /document\.addEventListener\("touchstart", startPluginBackSwipe, \{ passive: false, capture: true \}\)/);
  assert.doesNotMatch(appJs, /plugin_root_unhandled/);
  assert.match(appJs, /handlePluginBack\(\{\s*\n\s*preventDefault\(\) \{\},\s*\n\s*stopPropagation\(\) \{\},\s*\n\s*\}\);/);
  assert.match(appJs, /installPluginWindowingGuards\(\);\s*\n\s*installHermesPluginBackSwipeGuard\(\);/);
  assert.match(appJs, /const MAX_VISIBLE_TURNS = 10/);
  assert.match(appJs, /const MAX_EXPANDED_VISIBLE_TURNS = 200/);
  assert.match(appJs, /const THREAD_HISTORY_TOP_LOAD_PX = 64/);
  assert.match(appJs, /threadDetailMergePolicy\.mergeThreadPreservingVisibleItems\(existingThread, incomingThread/);
  assert.match(threadDetailMergeStateJs, /Boolean\(incomingThread\.mobileOlderTurnsCursor\)/);
  assert.match(threadDetailMergeStateJs, /Number\(incomingThread\.mobileOmittedTurnCount \|\| 0\) > 0/);
  assert.match(threadDetailMergeStateJs, /preservedExpandedTurnCount \+= 1/);
  assert.match(threadDetailMergeStateJs, /merged\.mobileOmittedTurnCount = Math\.max\(0, Number\(merged\.mobileOmittedTurnCount \|\| 0\) - preservedExpandedTurnCount\)/);
  assert.match(appJs, /function loadOlderThreadTurns\(options = \{\}\)/);
  assert.match(appJs, /const preserveScroll = Boolean\(options\.preserveScroll\)/);
  assert.match(appJs, /let newlyLoadedTurnCount = 0/);
  assert.match(appJs, /if \(!existingTurn\) newlyLoadedTurnCount \+= 1/);
  assert.match(appJs, /state\.currentThread\.mobileOmittedTurnCount = Math\.max\(0, Number\(state\.currentThread\.mobileOmittedTurnCount \|\| 0\) - newlyLoadedTurnCount\)/);
  assert.match(appJs, /renderCurrentThread\(\{ stickToBottom: false \}\)/);
  assert.match(appJs, /preserveConversationScrollAfterPrepend\(previousScrollTop, previousScrollHeight\)/);
  assert.match(appJs, /function maybeLoadOlderThreadTurnsFromScroll\(\)/);
  assert.match(appJs, /conversation\.scrollTop > THREAD_HISTORY_TOP_LOAD_PX/);
  assert.match(appJs, /loadOlderThreadTurns\(\{ preserveScroll: true, source: "scroll-top" \}\)/);
  assert.match(appJs, /maybeLoadOlderThreadTurnsFromScroll\(\);/);
  assert.match(appJs, /data-load-older-turns/);
  assert.match(appJs, /loadOlderThreadTurns\(\{ preserveScroll: true, source: "button" \}\)/);
  assert.match(appJs, /cursor: threadTurnsCursorParam\(cursor\)/);
  assert.match(appJs, /mobileHistoryExpanded = true/);
  assert.match(appJs, /function shouldBackfillFullThreadDetail\(thread\)/);
  assert.match(appJs, /turns-list-initial/);
  assert.match(appJs, /function threadDetailApiPath\(threadId, params = \{\}\)/);
  assert.match(appJs, /api\(threadDetailApiPath\(threadId, \{ mode: "recent" \}\)/);
  assert.match(appJs, /async function refreshCurrentThread\(options = \{\}\)/);
  assert.match(functionBody("refreshCurrentThread"), /const requestPlan = threadDetailRenderPlanApi\.planThreadDetailRefreshRequest\(\{/);
  assert.match(functionBody("refreshCurrentThread"), /threadId: state\.currentThreadId,[\s\S]*threadLoadSeq: state\.threadLoadSeq,[\s\S]*options,[\s\S]*hasActiveRefreshController: Boolean\(state\.refreshThreadController\),/);
  assert.match(functionBody("refreshCurrentThread"), /if \(!requestPlan\.shouldRefresh\) return;/);
  assert.match(functionBody("refreshCurrentThread"), /const requestedMode = requestPlan\.requestedMode;/);
  assert.match(functionBody("refreshCurrentThread"), /if \(requestPlan\.abortActiveRefresh && state\.refreshThreadController\) state\.refreshThreadController\.abort\(\);/);
  assert.match(functionBody("refreshCurrentThread"), /api\(threadDetailApiPath\(threadId, requestPlan\.query\), \{[\s\S]*timeoutMs: requestPlan\.timeoutMs,/);
  assert.doesNotMatch(functionBody("refreshCurrentThread"), /const requestedMode = options\.full === true \|\| String\(options\.mode \|\| ""\)\.toLowerCase\(\) === "full"/);
  assert.match(functionBody("refreshCurrentThread"), /recordHomeAiDiagnosticFailure\(threadDiagnosticEventsApi\.threadDetailRefreshFailedDiagnosticEvent\(\{[\s\S]*errorCode: diagnosticErrorCode\(err, "thread_detail_refresh_failed"\),[\s\S]*durationBucket: diagnosticDurationBucket\(roundedDurationMs\(refreshStartedAt\)\),[\s\S]*statusCode: diagnosticErrorStatus\(err\),[\s\S]*threadHash: diagnosticThreadHash\(threadId\),[\s\S]*\}\)\);/);
  assert.doesNotMatch(functionBody("refreshCurrentThread"), /recordHomeAiDiagnosticFailure\(\{[\s\S]*diagnostic_type: "thread_detail_refresh_failed"/);
  assert.match(appJs, /const previousConversationSignature = conversationRenderSignature\(state\.currentThread\);/);
  assert.match(appJs, /const threadDetailRenderPlanApi = window\.CodexThreadDetailRenderPlan;/);
  assert.match(appJs, /const previousPatchShellSignature = conversationPatchShellSignature\(previousThread\);/);
  assert.match(appJs, /threadDetailRenderPlanApi\.planThreadDetailRefreshRender\(\{[\s\S]*previousConversationSignature,[\s\S]*nextConversationSignature,[\s\S]*renderedConversationSignature: state\.renderedConversationSignature,[\s\S]*previousPatchShellSignature,[\s\S]*renderedPatchShellSignature: state\.renderedConversationPatchShellSignature,[\s\S]*\}\);/);
  assert.match(functionBody("refreshCurrentThread"), /const shouldRenderDetail = renderPlan\.shouldRenderDetail;/);
  assert.match(functionBody("refreshCurrentThread"), /const postMergePlan = threadDetailRenderPlanApi\.planThreadDetailRefreshPostMergeEffects\(\);/);
  assert.match(functionBody("refreshCurrentThread"), /applyThreadDetailRefreshPostMergeEffectsGroup\(postMergePlan, "merge"\);[\s\S]*const mergeMs = roundedDurationMs\(mergeStartedAt\);/);
  assert.match(functionBody("refreshCurrentThread"), /applyThreadDetailRefreshPostMergeEffectsGroup\(postMergePlan, "composer-render"\);[\s\S]*const composerRenderMs = roundedDurationMs\(composerRenderStartedAt\);/);
  assert.match(functionBody("refreshCurrentThread"), /applyThreadDetailRefreshPostMergeEffectsGroup\(postMergePlan, "thread-list-render"\);[\s\S]*const threadListRenderMs = roundedDurationMs\(threadListRenderStartedAt\);/);
  assert.doesNotMatch(functionBody("refreshCurrentThread"), /let detailRenderMode = renderPlan\.detailRenderMode;/);
  assert.doesNotMatch(functionBody("refreshCurrentThread"), /mergeThreadIntoThreadList\(state\.currentThread\);\s*const mergeMs/);
  assert.doesNotMatch(functionBody("refreshCurrentThread"), /renderComposerSettings\(\);\s*syncActiveTurnFromThread\(\);/);
  assert.match(functionBody("refreshCurrentThread"), /const patchSurfaceProbePlan = threadDetailRenderPlanApi\.planThreadDetailRefreshPatchSurface\(\{/);
  assert.match(functionBody("refreshCurrentThread"), /const tilePatchPlan = patchSurfaceProbePlan\.shouldProbeTilePatchSurface[\s\S]*\? threadDetailDomPatchSurface\(\{ threadId \}\)[\s\S]*: null;/);
  assert.match(functionBody("refreshCurrentThread"), /const patchSurfacePlan = threadDetailRenderPlanApi\.planThreadDetailRefreshPatchSurface\(\{[\s\S]*tilePatchSurface: tilePatchPlan && tilePatchPlan\.surface,[\s\S]*\}\);/);
  assert.match(functionBody("refreshCurrentThread"), /threadDetailRenderPlanApi\.planThreadDetailRefreshPatchExecution\(\{[\s\S]*shouldRenderDetail,[\s\S]*canPatch: renderPlan\.canPatch,[\s\S]*tileSurfaceRefresh,[\s\S]*\}\);/);
  assert.match(functionBody("refreshCurrentThread"), /tileSurfaceRefresh: patchSurfacePlan\.tileSurfaceRefresh/);
  assert.doesNotMatch(functionBody("refreshCurrentThread"), /tilePatchPlan && tilePatchPlan\.surface === "thread-tile-pane"/);
  assert.match(functionBody("refreshCurrentThread"), /const patchAttemptEffectsPlan = threadDetailRenderPlanApi\.planThreadDetailRefreshPatchAttemptEffects\(\{/);
  assert.match(functionBody("refreshCurrentThread"), /tryTilePanePatch: patchExecutionPlan\.tryTilePanePatch,[\s\S]*tryLocalPatch: patchExecutionPlan\.tryLocalPatch,/);
  assert.match(functionBody("refreshCurrentThread"), /const patchAttempt = applyThreadDetailRefreshPatchAttemptEffectsPlan\(patchAttemptEffectsPlan, \{/);
  assert.match(functionBody("refreshCurrentThread"), /const tilePanePatchAttempted = patchAttempt\.tilePanePatchAttempted;/);
  assert.match(functionBody("refreshCurrentThread"), /const localPatchAttempted = patchAttempt\.localPatchAttempted;/);
  assert.match(functionBody("refreshCurrentThread"), /const tilePanePatchMs = patchAttempt\.tilePanePatchMs;/);
  assert.match(functionBody("refreshCurrentThread"), /const localPatchMs = patchAttempt\.localPatchMs;/);
  assert.match(functionBody("refreshCurrentThread"), /tilePanePatchedDetail = patchAttempt\.tilePanePatchedDetail;/);
  assert.match(functionBody("refreshCurrentThread"), /locallyPatchedDetail = patchAttempt\.locallyPatchedDetail;/);
  assert.doesNotMatch(functionBody("refreshCurrentThread"), /if \(patchExecutionPlan\.tryTilePanePatch\)/);
  assert.doesNotMatch(functionBody("refreshCurrentThread"), /if \(shouldRenderDetail && !tilePanePatchedDetail && patchExecutionPlan\.tryLocalPatch\)/);
  assert.doesNotMatch(functionBody("refreshCurrentThread"), /renderPlan\.canPatch && !tileSurfaceRefresh/);
  assert.match(appJs, /function applyThreadDetailRefreshPatchAttemptEffectsPlan\(plan, context = \{\}\)/);
  assert.match(functionBody("applyThreadDetailRefreshPatchAttemptEffect"), /patchCurrentThreadTilePaneFromState\(\{[\s\S]*threadId: context\.threadId,[\s\S]*preserveScroll: item\.preserveScroll !== false,/);
  assert.match(functionBody("applyThreadDetailRefreshPatchAttemptEffect"), /patchCurrentThreadDetailFromRefresh\([\s\S]*context\.previousThread,[\s\S]*state\.currentThread,[\s\S]*context\.previousConversationSignature,/);
  assert.match(functionBody("applyThreadDetailRefreshPatchAttemptEffect"), /item\.skipWhenTilePanePatched && context\.tilePanePatchedDetail/);
  assert.match(functionBody("refreshCurrentThread"), /const patchAttemptResult = threadDetailRenderPlanApi\.planThreadDetailRefreshPatchAttemptResult\(\{/);
  assert.match(functionBody("refreshCurrentThread"), /tilePanePatchMs,[\s\S]*localPatchMs,[\s\S]*patchRejectReason: state\.threadDetailPatchRejectReason/);
  assert.doesNotMatch(functionBody("refreshCurrentThread"), /detailPatchMs = patchAttemptResult\.detailPatchMs;/);
  assert.match(functionBody("refreshCurrentThread"), /patchRejectReason = patchAttemptResult\.patchRejectReason;/);
  assert.match(functionBody("refreshCurrentThread"), /if \(patchAttemptResult\.reportLocalPatchRejected\) \{/);
  assert.match(functionBody("refreshCurrentThread"), /let renderOutcome = null;/);
  assert.match(functionBody("refreshCurrentThread"), /renderOutcome = threadDetailRenderPlanApi\.finalizeThreadDetailRenderPlan\(renderPlan, patchAttemptResult\.finalizeResult\);/);
  assert.doesNotMatch(functionBody("refreshCurrentThread"), /refreshRenderAction = renderOutcome\.renderAction;/);
  assert.match(functionBody("refreshCurrentThread"), /const executionPlan = threadDetailRenderPlanApi\.planThreadDetailRefreshOutcomeExecution\(renderOutcome\);/);
  assert.match(functionBody("refreshCurrentThread"), /const executionEffectsPlan = threadDetailRenderPlanApi\.planThreadDetailRefreshExecutionEffects\(executionPlan\);/);
  assert.match(functionBody("refreshCurrentThread"), /const executionTimings = applyThreadDetailRefreshExecutionEffectsPlan\(executionEffectsPlan\);/);
  assert.match(functionBody("refreshCurrentThread"), /metadataUpdateMs \+= executionTimings\.metadataUpdateMs;/);
  assert.match(functionBody("refreshCurrentThread"), /conversationRenderMs \+= executionTimings\.conversationRenderMs;/);
  assert.doesNotMatch(functionBody("refreshCurrentThread"), /for \(const effect of executionEffects\)/);
  assert.doesNotMatch(functionBody("refreshCurrentThread"), /executionPlan\.executionAction === "metadata-effects"/);
  assert.doesNotMatch(functionBody("refreshCurrentThread"), /executionPlan\.executionAction === "full-render"/);
  assert.match(appJs, /function applyThreadDetailRefreshExecutionEffectsPlan\(plan\)/);
  assert.match(functionBody("applyThreadDetailRefreshExecutionEffectsPlan"), /for \(const effect of effects\) \{/);
  assert.match(functionBody("applyThreadDetailRefreshExecutionEffectsPlan"), /applyThreadDetailRefreshExecutionEffect\(effect\)/);
  assert.match(appJs, /function applyThreadDetailRefreshExecutionEffect\(effect\)/);
  assert.match(functionBody("applyThreadDetailRefreshExecutionEffect"), /Thread detail refresh metadata effects are empty/);
  assert.match(functionBody("applyThreadDetailRefreshExecutionEffect"), /for \(const metadataEffect of metadataEffects\) applyThreadDetailRefreshMetadataEffect\(metadataEffect\);/);
  assert.match(functionBody("applyThreadDetailRefreshExecutionEffect"), /renderCurrentThread\(\);/);
  assert.match(functionBody("applyThreadDetailRefreshExecutionEffect"), /Unknown thread detail refresh execution action/);
  assert.match(functionBody("refreshCurrentThread"), /const consistencyCheck = executionPlan\.consistencyCheck \|\| \{\};/);
  assert.match(functionBody("refreshCurrentThread"), /if \(consistencyCheck\.shouldCheck\) \{[\s\S]*checkConversationProjectionConsistency\(consistencyCheck\.phase, \{ renderMode: consistencyCheck\.renderMode \}\);/);
  assert.match(appJs, /function applyThreadDetailRefreshMetadataEffect\(effect\)/);
  assert.match(functionBody("applyThreadDetailRefreshMetadataEffect"), /updateCurrentThreadHeader\(state\.currentThread\)/);
  assert.match(functionBody("applyThreadDetailRefreshMetadataEffect"), /updateLiveOperationDockHtml\(renderLiveOperationDock\(state\.currentThread, existingConversationRenderKeys\(\)\)\)/);
  assert.match(functionBody("applyThreadDetailRefreshMetadataEffect"), /publishPluginNavigationState\(\)/);
  assert.match(functionBody("applyThreadDetailRefreshMetadataEffect"), /scheduleScrollToBottomButtonUpdate\(\)/);
  assert.match(functionBody("refreshCurrentThread"), /const refreshPerformanceInput = threadDetailRenderPlanApi\.planThreadDetailRefreshPerformanceInput\(\{/);
  assert.match(functionBody("refreshCurrentThread"), /shouldRenderDetail,[\s\S]*renderPlan,[\s\S]*renderOutcome,[\s\S]*patchAttemptResult,[\s\S]*timings: \{/);
  assert.match(functionBody("refreshCurrentThread"), /const refreshPerformance = threadPerformanceMetrics\.threadDetailRefreshEventFields\(result\.thread, refreshPerformanceInput\);/);
  assert.match(functionBody("refreshCurrentThread"), /postPerformanceEvent\("thread_refresh_ms", refreshPerformance, \{/);
  assert.match(functionBody("refreshCurrentThread"), /const completionPlan = threadDetailRenderPlanApi\.planThreadDetailRefreshCompletionEffects\(\{[\s\S]*threadHash: diagnosticThreadHash\(threadId\),[\s\S]*\}\);/);
  assert.match(functionBody("refreshCurrentThread"), /for \(const effect of completionPlan\.effects\) applyThreadDetailRefreshCompletionEffect\(effect\);/);
  assert.match(appJs, /function applyThreadDetailRefreshCompletionEffect\(effect\)/);
  assert.match(functionBody("applyThreadDetailRefreshCompletionEffect"), /recordHomeAiDiagnosticSuccess\(item\.payload \|\| \{\}\)/);
  assert.match(functionBody("applyThreadDetailRefreshCompletionEffect"), /scheduleUsageBackfillRefresh\(\)/);
  assert.match(functionBody("applyThreadDetailRefreshCompletionEffect"), /scheduleLivePollIfNeeded\(\)/);
  assert.doesNotMatch(functionBody("refreshCurrentThread"), /recordHomeAiDiagnosticSuccess\(\{[\s\S]*thread_detail_refresh_failed/);
  assert.doesNotMatch(functionBody("refreshCurrentThread"), /skippedDetailRender: !shouldRenderDetail/);
  assert.match(appJs, /function rejectThreadDetailPatch\(reason\)/);
  assert.match(functionBody("patchCurrentThreadDetailFromRefresh"), /rejectThreadDetailPatch\("rendered-dom-stale"\)/);
  assert.match(functionBody("patchCurrentThreadDetailFromRefresh"), /rejectThreadDetailPatch\("patch-shell-changed"\)/);
  assert.match(appJs, /function conversationRootSignature\(thread\)/);
  assert.match(appJs, /function conversationPatchShellSignature\(thread\)/);
  assert.match(appJs, /renderedConversationPatchShellSignature: ""/);
  assert.match(functionBody("updateConversationHtml"), /threadDetailDomPatchApi\.planConversationHtmlUpdate\(\{/);
  assert.match(functionBody("updateConversationHtml"), /patchShellSignature: options\.patchShellSignature,/);
  assert.match(functionBody("updateConversationHtml"), /state\.renderedConversationPatchShellSignature = updatePlan\.nextRenderedConversationPatchShellSignature;/);
  assert.match(appJs, /function rolloutWarningSignature\(thread\)/);
  assert.doesNotMatch(functionBody("conversationRootSignature"), /rolloutSizeBytes: rolloutSizeBytes\(thread\)/);
  assert.doesNotMatch(functionBody("conversationRenderSignature"), /rolloutSizeBytes: rolloutSizeBytes\(thread\)/);
  assert.match(functionBody("conversationRootSignature"), /rolloutWarning: rolloutWarningSignature\(thread\)/);
  assert.match(functionBody("conversationPatchShellSignature"), /rolloutWarning: rolloutWarningSignature\(thread\)/);
  assert.doesNotMatch(functionBody("conversationPatchShellSignature"), /projectionRevision/);
  assert.doesNotMatch(functionBody("conversationPatchShellSignature"), /visibleItemKeys/);
  assert.match(functionBody("conversationRenderSignature"), /rolloutWarning: rolloutWarningSignature\(thread\)/);
  assert.match(functionBody("conversationRootSignature"), /visibleTurns: turns\.map\(\(turn\) => turn && \(turn\.id \|\| turn\.startedAt \|\| ""\)\)/);
  assert.match(appJs, /function patchVisibleItemDom\(turn, item\)/);
  assert.match(appJs, /function insertVisibleItemDom\(turn, item\)/);
  assert.match(appJs, /function insertTurnArticleDom\(turn, previousKeys = existingConversationRenderKeys\(\)\)/);
  assert.match(appJs, /function insertTurnArticleElementDom\(turn, source\)/);
  assert.match(appJs, /function patchCurrentThreadDetailFromRefresh\(previousThread, nextThread, previousConversationSignature\)/);
  assert.match(functionBody("patchCurrentThreadDetailFromRefresh"), /const previousPatchShellSignature = conversationPatchShellSignature\(previousThread\);/);
  assert.match(functionBody("patchCurrentThreadDetailFromRefresh"), /state\.renderedConversationSignature !== previousConversationSignature[\s\S]*renderedPatchShellSignature !== previousPatchShellSignature/);
  assert.match(functionBody("patchCurrentThreadDetailFromRefresh"), /previousPatchShellSignature !== conversationPatchShellSignature\(nextThread\)/);
  assert.match(functionBody("patchCurrentThreadDetailFromRefresh"), /updateLiveOperationDockHtml\(renderLiveOperationDock\(nextThread, previousKeys\)\)/);
  assert.match(functionBody("patchCurrentThreadDetailFromRefresh"), /patchNode\(article, source\);/);
  assert.match(functionBody("insertVisibleItemDom"), /if \(isOperationalItem\(item\)\) return updateLiveOperationDockForLocalPatch\(\);/);
  assert.match(functionBody("insertVisibleItemDom"), /article = insertTurnArticleDom\(turn, previousKeys\);/);
  assert.match(functionBody("insertVisibleItemDom"), /threadDetailDomPatchApi\.insertVisibleItemElement\(\{/);
  assert.doesNotMatch(functionBody("insertVisibleItemDom"), /for \(let index = visibleIndex - 1/);
  assert.match(functionBody("insertTurnArticleElementDom"), /threadDetailDomPatchApi\.insertTurnArticleElement/);
  assert.doesNotMatch(functionBody("insertTurnArticleElementDom"), /for \(let index = turnIndex - 1/);
  assert.match(functionBody("turnArticleNode"), /threadDetailDomPatchApi\.findTurnArticleElement/);
  assert.match(functionBody("turnArticleNode"), /turnKey: key/);
  assert.doesNotMatch(functionBody("turnArticleNode"), /conversation\.querySelector\(`\[data-render-key=/);
  assert.match(functionBody("firstElementFromHtml"), /threadDetailDomPatchApi\.createElementFromHtml/);
  assert.match(functionBody("insertTurnArticleDom"), /threadDetailDomPatchApi\.createTurnArticleElement/);
  assert.match(functionBody("patchCurrentThreadDetailFromRefresh"), /renderTurnElement: \(turn\) => threadDetailDomPatchApi\.createTurnArticleElement/);
  assert.match(functionBody("hydrateThreadDetailSurface"), /threadDetailDomPatchApi\.hydrateRenderedSurface/);
  assert.match(functionBody("updateConversationHtml"), /hydrateThreadDetailSurface\(conversation/);
  assert.match(functionBody("patchThreadTilePane"), /hydrateThreadDetailSurface\(patchedPane, \{ imageScanDelays: \[0, 180\] \}\)/);
  assert.match(functionBody("completeLocalConversationDomUpdate"), /threadDetailDomPatchApi\.planLocalConversationDomUpdateCompletion\(\{/);
  assert.match(functionBody("completeLocalConversationDomUpdate"), /if \(completionPlan\.hydrateRoot\) hydrateThreadDetailSurface\(root, completionPlan\.hydrateOptions \|\| \{\}\);/);
  assert.match(functionBody("upsertItem"), /if \(structureChanged\) scheduleRenderCurrentThread\(\);[\s\S]*else if \(canPatchExistingItem\)[\s\S]*else if \(!insertVisibleItemDom\(turn, nextItem\)\)/);
  assert.match(functionBody("appendToItem"), /if \(isOperationalItem\(item\)\) updateLiveOperationDockForLocalPatch\(\);[\s\S]*else if \(createdItem\) \{/);
  assert.match(stylesCss, /\.live-operation-dock\s*{[\s\S]*min-height:\s*var\(--live-operation-dock-compact-height, 40px\);[\s\S]*contain:\s*layout paint;/);
  assert.match(stylesCss, /\.live-operation-dock:not\(\[data-mode="expanded"\]\)\s*{[\s\S]*height:\s*var\(--live-operation-dock-compact-height, 40px\);/);
  assert.match(stylesCss, /\.live-operation-dock:not\(\[data-mode="expanded"\]\) \.live-operation\s*{[\s\S]*height:\s*32px;[\s\S]*max-height:\s*32px;/);
  assert.match(stylesCss, /@media \(pointer: coarse\)[\s\S]*\.live-operation-dock\s*{[\s\S]*position:\s*fixed;[\s\S]*bottom:\s*calc\(var\(--composer-height, 92px\) \+ 8px\);/);
  assert.match(stylesCss, /@media \(pointer: coarse\)[\s\S]*\.live-operation-dock-desktop\s*{[\s\S]*display:\s*none;/);
  assert.match(stylesCss, /@media \(pointer: coarse\)[\s\S]*\.mobile-operation-stack\s*{[\s\S]*display:\s*grid;/);
  assert.match(stylesCss, /@media \(max-width: 760px\)[\s\S]*\.live-operation-dock\s*{[\s\S]*position:\s*fixed;[\s\S]*bottom:\s*calc\(var\(--composer-height, 92px\) \+ 8px\);/);
  assert.match(stylesCss, /@media \(max-width: 760px\)[\s\S]*\.live-operation-dock:not\(\[data-mode="expanded"\]\)\s*{[\s\S]*height:\s*auto;/);
  assert.match(stylesCss, /@media \(max-width: 760px\)[\s\S]*\.mobile-operation-bubble\s*{[\s\S]*max-width:\s*min\(78vw, 420px\);/);
  assert.match(stylesCss, /@media \(max-width: 760px\)[\s\S]*\.mobile-operation-sheet\s*{[\s\S]*max-height:\s*min\(42vh, 280px\);/);
  assert.match(appJs, /if \(shouldBackfillFullThreadDetail\(result\.thread\)\) \{/);
  assert.match(appJs, /backfillFullThreadDetail\(threadId, \{ seq, source \}\)\.catch\(\(\) => \{\}\)/);
  assert.match(functionBody("backfillFullThreadDetail"), /threadPerformanceMetrics\.threadDetailFullReadyEventFields\(result\.thread, \{/);
  assert.match(functionBody("backfillFullThreadDetail"), /postPerformanceEvent\("thread_detail_full_ready", fullReadyPerformance, \{ force: true \}\)/);
  assert.match(stylesCss, /\.history-loader\s*{[\s\S]*justify-content:\s*space-between;/);
  assert.match(stylesCss, /\.history-load-button/);
  assert.match(swJs, /"\/api-client\.js"/);
  assert.match(swJs, /"\/runtime-settings\.js"/);
  assert.match(swJs, /"\/draft-store\.js"/);
  assert.match(swJs, /"\/markdown-renderer\.js"/);
  assert.match(swJs, /"\/viewport-metrics\.js"/);
  assert.match(swJs, /"\/conversation-scroll\.js"/);
  assert.match(swJs, /"\/image-compressor\.js"/);
  assert.match(swJs, /"\/plugin-embed\.js"/);
  assert.match(swJs, /"\/home-ai-diagnostic-reporting\.js"/);
  assert.match(swJs, /"\/thread-diagnostic-events\.js"/);
  assert.match(swJs, /"\/thread-performance-metrics\.js"/);
  assert.match(swJs, /"\/live-operation-dock-state\.js"/);
  assert.match(swJs, /"\/thread-detail-state\.js"/);
  assert.match(swJs, /"\/thread-detail-render-plan\.js"/);
  assert.match(swJs, /"\/thread-detail-merge-state\.js"/);
  assert.match(swJs, /"\/thread-detail-patch-plan\.js"/);
  assert.match(swJs, /"\/thread-detail-dom-patch\.js"/);
  assert.match(swJs, /"\/thread-detail-actions\.js"/);
  assert.match(swJs, /"\/thread-tile-actions\.js"/);
  assert.match(swJs, /"\/thread-tile-state\.js"/);
  assert.match(swJs, /"\/thread-tile-layout\.js"/);
  assert.match(swJs, /"\/build-refresh-policy\.js"/);
  assert.match(appJs, /"\/viewport-metrics\.js"/);
  assert.match(appJs, /"\/conversation-scroll\.js"/);
  assert.match(appJs, /"\/image-compressor\.js"/);
  assert.match(appJs, /"\/plugin-embed\.js"/);
  assert.match(appJs, /"\/home-ai-diagnostic-reporting\.js"/);
  assert.match(appJs, /"\/thread-diagnostic-events\.js"/);
  assert.match(appJs, /"\/thread-performance-metrics\.js"/);
  assert.match(appJs, /"\/live-operation-dock-state\.js"/);
  assert.match(appJs, /"\/thread-detail-state\.js"/);
  assert.match(appJs, /"\/thread-detail-render-plan\.js"/);
  assert.match(appJs, /"\/thread-detail-merge-state\.js"/);
  assert.match(appJs, /"\/thread-detail-patch-plan\.js"/);
  assert.match(appJs, /"\/thread-detail-dom-patch\.js"/);
  assert.match(appJs, /"\/thread-detail-actions\.js"/);
  assert.match(appJs, /"\/thread-tile-actions\.js"/);
  assert.match(appJs, /"\/thread-tile-state\.js"/);
  assert.match(appJs, /"\/thread-tile-layout\.js"/);
  assert.match(appJs, /"\/build-refresh-policy\.js"/);
  assert.match(appJs, /navigator\.serviceWorker\.register\("\/sw\.js"\)/);
  assert.match(appJs, /state\.serviceWorkerRegistration\.update\(\)\.catch/);
  assert.match(swJs, /if \(!data\.threadId && payload\.threadId\) data\.threadId = payload\.threadId;/);
  assert.match(swJs, /if \(threadId && !url\.searchParams\.get\("thread"\)\) \{/);
  assert.match(swJs, /url\.searchParams\.set\("thread", threadId\);/);
  assert.match(swJs, /self\.clients\.openWindow\(target\.url\)/);
  assert.match(indexHtml, /id="workspaceTokenUsage"/);
  assert.match(indexHtml, /id="workspaceStatsDialog"/);
  assert.match(appJs, /workspaceTokenUsage: null/);
  assert.match(appJs, /function renderWorkspaceTokenUsage\(\)/);
  assert.match(appJs, /function renderWorkspaceStatsDialog\(\)/);
  assert.match(appJs, /data-workspace-token-usage-toggle>统计<\/button>/);
  assert.match(appJs, /function formatTokenMillion\(value\)/);
  assert.match(appJs, /const THREAD_LIST_PAGE_LIMIT = 40;/);
  assert.match(appJs, /new URLSearchParams\(\{ limit: String\(THREAD_LIST_PAGE_LIMIT\), archived: "false" \}\)/);
  assert.match(appJs, /function hasThreadDetailRequestInFlight\(\)/);
  assert.match(appJs, /state\.threadLoadController[\s\S]*state\.refreshThreadController[\s\S]*state\.currentThread && state\.currentThread\.mobileLoading/);
  assert.match(appJs, /const threadDetailOpening = hasThreadDetailRequestInFlight\(\);/);
  assert.match(appJs, /silent && options\.deferFallback !== false && threadDetailOpening && !state\.selectedCwd && !search/);
  assert.match(appJs, /if \(shouldDeferFallback && !search\) params\.set\("fallback", "defer"\)/);
  assert.match(appJs, /const THREAD_LIST_DEFERRED_FALLBACK_DELAY_MS = 8000;/);
  assert.match(appJs, /const THREAD_LIST_DEFERRED_FALLBACK_RETRY_MS = 2500;/);
  assert.match(appJs, /threadListDeferredFallbackTimer: null/);
  assert.match(appJs, /function scheduleThreadListDeferredFallback\(delayMs = THREAD_LIST_DEFERRED_FALLBACK_DELAY_MS\)/);
  assert.match(appJs, /if \(state\.threadListLoadController \|\| hasThreadDetailRequestInFlight\(\)\) \{[\s\S]*scheduleThreadListDeferredFallback\(THREAD_LIST_DEFERRED_FALLBACK_RETRY_MS\);[\s\S]*return;/);
  assert.match(appJs, /if \(options\.deferFallback !== true\) clearThreadListDeferredFallbackTimer\(\);/);
  assert.match(appJs, /if \(result && result\.mobileDeferredFallback && !state\.selectedCwd && !search\) \{[\s\S]*scheduleThreadListDeferredFallback\(\);[\s\S]*\}/);
  assert.match(appJs, /Uncached \$\{escapeHtml\(formatTokenMillion\(displayInputTokensExcludingCached\(entry\)\)\)\}/);
  assert.match(appJs, /Cached \$\{escapeHtml\(formatTokenMillion\(entry && entry\.cachedInputTokens\)\)\}/);
  assert.match(appJs, /Out \$\{escapeHtml\(formatTokenMillion\(entry && entry\.outputTokens\)\)\}/);
  assert.match(appJs, /Reason \$\{escapeHtml\(formatTokenMillion\(entry && entry\.reasoningOutputTokens\)\)\}/);
  assert.match(stylesCss, /\.workspace-token-usage/);
  assert.match(stylesCss, /\.workspace-token-usage-summary span[\s\S]*color:\s*var\(--danger-text\)/);
  assert.match(stylesCss, /\.workspace-stats-dialog/);
  assert.match(stylesCss, /\.workspace-stats-breakdown/);
});

test("Android back and edge swipe open the mobile navigation menu", () => {
  assert.match(appJs, /const ANDROID_SIDEBAR_EDGE_SWIPE_PX = 44/);
  assert.match(appJs, /const ANDROID_BACK_SIDEBAR_BASE = "base"/);
  assert.match(appJs, /const ANDROID_BACK_SIDEBAR_TOP = "top"/);
  assert.match(appJs, /function sidebarTransformIsNone\(transform\)/);
  assert.match(appJs, /matrix\(1,0,0,1,0,0\)/);
  assert.match(appJs, /matrix3d\(1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1\)/);
  assert.match(appJs, /function splitPaneSidebarVisible\(\)/);
  assert.match(appJs, /Number\(rect\.width \|\| 0\) < 80 \|\| Number\(rect\.height \|\| 0\) < 80/);
  assert.match(appJs, /style\.position === "fixed"/);
  assert.match(appJs, /return sidebarTransformIsNone\(style\.transform\)/);
  assert.match(appJs, /const HOST_EMBED_SPLIT_LEFT_MIN_PX = 160/);
  assert.match(appJs, /const HOST_EMBED_SPLIT_VIEWPORT_MIN_PX = 900/);
  assert.match(appJs, /function hostEmbeddedSplitPaneVisible\(\)/);
  assert.match(appJs, /frameLeft >= HOST_EMBED_SPLIT_LEFT_MIN_PX/);
  assert.match(appJs, /frameWidth < hostWidth - 24/);
  assert.match(appJs, /function threadDetailReturnButtonVisible\(\)/);
  assert.match(appJs, /if \(isHermesEmbedMode\(\)\) return hostEmbeddedSplitPaneVisible\(\)/);
  assert.match(appJs, /function syncThreadDetailLayoutState\(\)/);
  assert.match(appJs, /document\.documentElement\.classList\.toggle\("thread-detail-active", detailActive\)/);
  assert.match(appJs, /const splitReturn = threadDetailReturnButtonVisible\(\)/);
  assert.match(appJs, /openMenuButton\.classList\.toggle\("split-return-visible", splitReturn\)/);
  assert.match(appJs, /openMenuButton\.textContent = splitReturn \? "←" : "☰"/);
  assert.match(appJs, /function returnToThreadListFromDetail\(\)/);
  assert.match(appJs, /clearCurrentThreadSelection\(\);[\s\S]*renderThreads\(\);[\s\S]*renderCurrentThread\(\);/);
  assert.match(appJs, /function handleOpenMenuClick\(\)/);
  assert.match(appJs, /if \(threadDetailReturnButtonVisible\(\) && returnToThreadListFromDetail\(\)\) return;/);
  assert.match(appJs, /\$\("openMenu"\)\.addEventListener\("click", handleOpenMenuClick\)/);
  assert.doesNotMatch(stylesCss, /html\.thread-detail-active #openMenu\.mobile-only\s*{[\s\S]*display:\s*grid;/);
  assert.match(stylesCss, /#openMenu\.split-return-visible\s*{[\s\S]*display:\s*grid;/);
  assert.match(stylesCss, /html\.embed-hermes #openMenu,[\s\S]*html\.embed-hermes \.main \.version-actions\s*{[\s\S]*display:\s*none !important;/);
  assert.match(stylesCss, /html\.embed-hermes #openMenu\.split-return-visible\s*{[\s\S]*display:\s*grid !important;/);
  assert.doesNotMatch(stylesCss, /html\.embed-hermes\.thread-detail-active #openMenu\.mobile-only/);
  assert.match(appJs, /function isAndroidBrowser\(\)/);
  assert.match(appJs, /function sidebarEdgeSwipeStartLimitPx\(\)/);
  assert.match(appJs, /function pointInComposerGestureZone\(point\)/);
  assert.match(appJs, /\.composer-controls/);
  assert.match(appJs, /point\.clientY >= Math\.max\(0, rect\.top - 10\)/);
  assert.match(appJs, /if \(pointInComposerGestureZone\(touch\)\) return;/);
  assert.match(appJs, /touch\.clientX > sidebarEdgeSwipeStartLimitPx\(\)/);
  assert.match(appJs, /ensureAndroidBackToSidebarSentinel\(\);[\s\S]*if \(event\.cancelable !== false\) event\.preventDefault\(\);/);
  assert.match(appJs, /if \(event\.cancelable !== false\) event\.preventDefault\(\);/);
  assert.match(appJs, /addEventListener\("touchstart", beginSidebarEdgeSwipe, \{ passive: false \}\)/);
  assert.match(appJs, /function ensureAndroidBackToSidebarSentinel\(\)/);
  assert.match(appJs, /\$\("app"\)\.classList\.remove\("hidden"\);[\s\S]*ensureAndroidBackToSidebarSentinel\(\);/);
  assert.match(appJs, /window\.history\.replaceState\(Object\.assign\(\{\}, currentState,[\s\S]*ANDROID_BACK_SIDEBAR_BASE/);
  assert.match(appJs, /window\.history\.pushState\(Object\.assign\(\{\}, currentState,[\s\S]*ANDROID_BACK_SIDEBAR_TOP/);
  assert.match(appJs, /function handleAndroidBackToSidebarPopState\(event\)/);
  assert.match(appJs, /&& state\.key/);
  assert.match(appJs, /&& !app\.classList\.contains\("hidden"\)/);
  assert.match(appJs, /if \(!isSidebarOpen\(\)\) openSidebarMenu\(\);/);
  assert.match(appJs, /if \(document\.visibilityState === "visible"\) \{[\s\S]*ensureAndroidBackToSidebarSentinel\(\);/);
  assert.match(appJs, /window\.addEventListener\("pageshow",[\s\S]*ensureAndroidBackToSidebarSentinel\(\);/);
  assert.match(appJs, /window\.addEventListener\("focus",[\s\S]*ensureAndroidBackToSidebarSentinel\(\);/);
  assert.match(appJs, /window\.addEventListener\("popstate", handleAndroidBackToSidebarPopState\)/);
});

test("workspace creation lives at the bottom of the Workspace menu", () => {
  assert.match(indexHtml, /id="workspaceSelectMenu"/);
  assert.match(indexHtml, /id="newThreadButton"/);
  assert.match(indexHtml, /id="createWorkspaceDialog"/);
  assert.match(indexHtml, /id="createWorkspaceForm"/);
  assert.match(indexHtml, /id="createWorkspaceRootSelect"/);
  assert.match(appJs, /function workspaceSidebarOptionsHtml\(\)/);
  assert.match(appJs, /data-create-workspace/);
  assert.match(appJs, /return allOption \+ workspaceOptions \+ createOption;/);
  assert.match(appJs, /openCreateWorkspaceDialog\(\)/);
  assert.match(appJs, /function populateCreateWorkspaceRootSelect\(\)/);
  assert.match(appJs, /body:\s*JSON\.stringify\(\{\s*name,\s*parent:\s*workspaceCreateSelectedRoot\(\)\s*\}\)/);
  assert.match(appJs, /api\("\/api\/workspaces", \{[\s\S]*method: "POST"/);
  assert.match(stylesCss, /\.workspace-create-option/);
  assert.match(stylesCss, /\.create-workspace-root-select/);
  assert.doesNotMatch(indexHtml, /newThreadButton[\s\S]{0,240}createWorkspace/i);
});

test("push notification control stays hidden when the browser cannot enable it", () => {
  assert.doesNotMatch(appJs, /HTTPS required/);
  assert.doesNotMatch(appJs, /Notifications unavailable/);
  assert.doesNotMatch(appJs, /Notifications unsupported/);
  assert.match(appJs, /const hideButton = \(\) => \{/);
  assert.match(appJs, /if \(!window\.isSecureContext\) \{[\s\S]*hideButton\(\);[\s\S]*return;[\s\S]*\}/);
});
