"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { test } = require("node:test");

const indexHtml = fs.readFileSync(path.resolve(__dirname, "..", "public", "index.html"), "utf8");
const appJs = fs.readFileSync(path.resolve(__dirname, "..", "public", "app.js"), "utf8");
const stylesCss = fs.readFileSync(path.resolve(__dirname, "..", "public", "styles.css"), "utf8");
const swJs = fs.readFileSync(path.resolve(__dirname, "..", "public", "sw.js"), "utf8");
const viewportMetricsJs = fs.readFileSync(path.resolve(__dirname, "..", "public", "viewport-metrics.js"), "utf8");

test("mobile viewport and early guards disable page zoom", () => {
  assert.match(indexHtml, /name="viewport" content="[^"]*maximum-scale=1/);
  assert.match(indexHtml, /name="viewport" content="[^"]*minimum-scale=1/);
  assert.match(indexHtml, /name="viewport" content="[^"]*user-scalable=no/);
  assert.match(indexHtml, /addEventListener\("gesturestart", preventZoom, \{ passive: false \}\)/);
  assert.match(indexHtml, /addEventListener\("gesturechange", preventZoom, \{ passive: false \}\)/);
  assert.match(indexHtml, /addEventListener\("dblclick", preventZoom, \{ passive: false \}\)/);
  assert.match(indexHtml, /lastTouchEndAt < 320/);
  assert.match(indexHtml, /<script src="\/viewport-metrics\.js"><\/script>/);
  assert.match(indexHtml, /<script src="\/conversation-scroll\.js"><\/script>/);
  assert.match(indexHtml, /<script src="\/image-compressor\.js"><\/script>/);
  assert.match(indexHtml, /<script src="\/plugin-embed\.js"><\/script>/);
  assert.match(appJs, /const viewportMetrics = window\.CodexViewportMetrics/);
  assert.match(appJs, /viewportMetrics\.measureViewport\(\{/);
  assert.match(viewportMetricsJs, /const keyboardShrunk = keyboardCandidate && keyboardInputActive/);
  assert.match(viewportMetricsJs, /const height = keyboardShrunk \? visualBottom : Math\.max\(visualBottom \|\| 0, layout \|\| 0\)/);
  assert.match(appJs, /if \(viewport\.keyboardShrunk\) \{[\s\S]*--app-height/);
  assert.match(appJs, /document\.documentElement\.style\.removeProperty\("--app-height"\)/);
  assert.match(appJs, /document\.documentElement\.classList\.toggle\("keyboard-open", viewport\.keyboardShrunk\)/);
  assert.match(stylesCss, /html,\s*\nbody\s*{[\s\S]*touch-action:\s*pan-x pan-y;/);
  assert.match(stylesCss, /html\s*{[\s\S]*height:\s*-webkit-fill-available;/);
  assert.match(stylesCss, /body\s*{[\s\S]*min-height:\s*-webkit-fill-available;/);
  assert.match(stylesCss, /html\.embed-hermes \.composer\s*{[\s\S]*padding-bottom:\s*clamp\(12px, calc\(env\(safe-area-inset-bottom, 0px\) - 82px\), 56px\);/);
  assert.match(stylesCss, /html\.embed-hermes\.keyboard-open \.composer\s*{[\s\S]*padding-bottom:\s*10px;/);
  assert.match(stylesCss, /html\.embed-hermes \.main \.version-actions/);
  assert.match(indexHtml, /id="continuationDialog"/);
  assert.match(appJs, /function openContinuationDialog\(/);
  assert.match(appJs, /function continuationDialogOpen\(/);
  assert.match(appJs, /function closeContinuationDialog\(/);
  assert.match(stylesCss, /\.continuation-dialog/);
  assert.match(stylesCss, /html\.keyboard-open \.composer\s*{[\s\S]*padding-bottom:\s*12px;/);
  assert.match(stylesCss, /@media \(max-width: 760px\)[\s\S]*\.composer\s*{[\s\S]*gap:\s*6px;[\s\S]*padding:\s*7px 12px clamp\(8px, calc\(env\(safe-area-inset-bottom, 0px\) - 88px\), 52px\);/);
  assert.match(stylesCss, /@media \(max-width: 760px\)[\s\S]*html\.embed-hermes \.composer\s*{[\s\S]*padding-bottom:\s*clamp\(8px, calc\(env\(safe-area-inset-bottom, 0px\) - 84px\), 56px\);/);
  assert.match(stylesCss, /@media \(max-width: 760px\)[\s\S]*html\.embed-hermes\.keyboard-open \.composer\s*{[\s\S]*padding-bottom:\s*8px;/);
  assert.match(stylesCss, /@media \(max-width: 760px\)[\s\S]*html\.keyboard-open \.composer\s*{[\s\S]*padding-bottom:\s*7px;/);
});

test("public app shell cache advances after Fast control and refresh prompt hardening", () => {
  assert.match(swJs, /codex-mobile-shell-v218/);
  assert.match(appJs, /CLIENT_BUILD_ID = "0\.1\.11\|codex-mobile-shell-v218"/);
  assert.match(appJs, /function serverBuildIdFromConfig\(config\) \{\s*return String\(config && \(config\.clientBuildId \|\| config\.shellCacheName \|\| config\.buildId\) \|\| ""\)\.trim\(\);/);
  assert.doesNotMatch(appJs, /function serverBuildIdFromConfig\(config\) \{\s*return String\(config && \(config\.clientBuildId \|\| config\.shellCacheName \|\| config\.buildId \|\| config\.version\)/);
  assert.match(appJs, /startupThreadOpenPending: false/);
  assert.match(indexHtml, /id="pluginStartupLoading"/);
  assert.match(indexHtml, /data-plugin-startup-title>正在加载 Codex\.\.\.</);
  assert.match(appJs, /pluginStartupLoading: Boolean\(INITIAL_PLUGIN_EMBED\.embedded\)/);
  assert.match(appJs, /function showPluginStartupLoading\(message = ""\)/);
  assert.match(appJs, /function hidePluginStartupLoading\(\)/);
  assert.match(appJs, /if \(isHermesEmbedMode\(\)\) showPluginStartupLoading\(\);/);
  assert.match(appJs, /hidePluginStartupLoading\(\);[\s\S]*}\s*\n\s*function threadIdFromUrlValue/);
  assert.match(stylesCss, /html\.embed-hermes\.plugin-startup-loading \.app/);
  assert.match(stylesCss, /\.plugin-startup-loading\s*{[\s\S]*position:\s*fixed;[\s\S]*place-items:\s*center;/);
  assert.doesNotMatch(appJs, /thread-card-token-badge/);
  assert.doesNotMatch(stylesCss, /thread-card-token-badge/);
  assert.match(appJs, /const savedThreadId = isHermesEmbedMode\(\) \? "" : \(localStorage\.getItem\(STORAGE_THREAD_ID\) \|\| ""\);/);
  assert.match(appJs, /function hasStartupThreadOpenIntent\(\)/);
  assert.match(appJs, /postClientEvent\("startup_stage"/);
  assert.match(appJs, /state\.startupThreadOpenPending = hasStartupThreadOpenIntent\(\);[\s\S]*early_opening_rendered/);
  assert.match(appJs, /postStartupStage\("public_config_done"/);
  assert.match(appJs, /state\.startupThreadOpenPending = Boolean\(startupThreadId \|\| savedThreadId \|\| \(startupPluginRouteHint && startupPluginRouteHint\.threadId\)\);/);
  assert.match(appJs, /const earlyRestorePromise = savedThreadId && !startupThreadId[\s\S]*loadThread\(savedThreadId, \{ source: "restore-startup" \}\)/);
  assert.match(appJs, /postStartupStage\("status_done"/);
  assert.match(appJs, /postStartupStage\("threads_done"/);
  assert.match(appJs, /startupInProgress: false/);
  assert.match(appJs, /mobile_resume_skipped_startup/);
  assert.match(appJs, /await loadThreads\(\{ silent: startupThreadOpenPending \}\);/);
  assert.match(appJs, /function renderStartupThreadOpening\(\)/);
  assert.match(appJs, /Opening thread\.\.\./);
  assert.match(appJs, /if \(state\.startupThreadOpenPending\) \{[\s\S]*renderStartupThreadOpening\(\);[\s\S]*return;/);
  assert.match(appJs, /function showPluginEmbedRecovering\(message = ""\)/);
  assert.match(appJs, /Refreshing Codex Mobile plugin session\.\.\./);
  assert.match(appJs, /Refreshing Codex Mobile plugin launch\.\.\./);
  assert.match(appJs, /Refreshing plugin page from Hermes Mobile\.\.\./);
  assert.match(appJs, /state\.pluginRefreshPendingTimer = window\.setTimeout\(\(\) => \{/);
  assert.match(appJs, /function clearPluginRefreshPendingNotice\(\)/);
  assert.match(appJs, /Generating cross-thread task card draft\.\.\./);
  assert.match(stylesCss, /\.plugin-refresh-pending/);
  assert.match(stylesCss, /\.approval-details/);
  assert.match(stylesCss, /\.approval-summary-line/);
  assert.match(appJs, /if \(threadId === state\.currentThreadId && state\.currentThread && !state\.currentThread\.mobileLoadError\) \{/);
  assert.match(appJs, /scheduleCurrentThreadRefresh\(250\);[\s\S]*openExternalThreadSelection\(threadId\)\.catch\(showError\);/);
  assert.match(appJs, /function currentThreadNeedsForegroundRefresh\(\)/);
  assert.match(appJs, /function currentThreadListRowChanged\(\)/);
  assert.match(appJs, /threadUpdatedAtMs\(row\)/);
  assert.match(appJs, /mobile_resume_thread_refresh_skipped/);
  assert.match(appJs, /if \(state\.currentThreadId && state\.currentThread && !state\.currentThread\.mobileLoading && !state\.currentThread\.mobileLoadError\) \{/);
  assert.match(appJs, /return shouldPollCurrentThread\(\) \|\| currentThreadListRowChanged\(\);/);
  assert.match(appJs, /if \(currentThreadNeedsForegroundRefresh\(\)\) \{[\s\S]*scheduleCurrentThreadRefresh\(250\);[\s\S]*mobile_resume_thread_refresh_skipped[\s\S]*else if \(state\.currentThreadId\) \{[\s\S]*await refreshCurrentThread\(\);[\s\S]*else \{[\s\S]*await restoreThreadSelection\(\);/);
  assert.match(appJs, /async function restoreThreadSelection\(\) \{[\s\S]*if \(isHermesEmbedMode\(\)\) \{[\s\S]*showHermesPluginPrimaryPage\(\);[\s\S]*return;/);
  assert.match(appJs, /renderCurrentThread\(\{ stickToBottom: true \}\);\s*\n\s*publishPluginNavigationState\(\{ force: true \}\);\s*\n\s*updateComposerControls\(\);/);
  assert.doesNotMatch(appJs, /function shouldOpenLargeThreadHistoryAtTop/);
  assert.doesNotMatch(appJs, /function threadOpenRenderOptions/);
  assert.doesNotMatch(appJs, /scrollConversationToTop/);
  assert.doesNotMatch(appJs, /scrollToTop/);
  assert.match(appJs, /const explicitNoStickToBottom = options\.stickToBottom === false \|\| Boolean\(options\.scrollToTurnReceiptStart\);/);
  assert.match(appJs, /renderCurrentThread\(\{ stickToBottom: true \}\);\s*\n\s*if \(isMenuOverlayMode\(\)\) closeSidebarMenu\(\);/);
  assert.match(appJs, /renderCurrentThread\(\{ stickToBottom: true \}\);\s*\n\s*publishPluginNavigationState\(\{ force: true \}\);\s*\n\s*restoreConnectionState\(\);/);
  assert.match(appJs, /const PLUGIN_EMBED_BACK_EDGE_SWIPE_PX = 44/);
  assert.match(appJs, /function installHermesPluginBackSwipeGuard\(\)/);
  assert.match(appJs, /pluginEmbedApi\.navigationMessage\(state, pluginNavigationUiState\(\)\)/);
  assert.match(appJs, /document\.addEventListener\("touchstart", startPluginBackSwipe, \{ passive: false, capture: true \}\)/);
  assert.match(appJs, /handlePluginBack\(\{\s*\n\s*preventDefault\(\) \{\},\s*\n\s*stopPropagation\(\) \{\},\s*\n\s*\}\);/);
  assert.match(appJs, /installPluginWindowingGuards\(\);\s*\n\s*installHermesPluginBackSwipeGuard\(\);/);
  assert.match(appJs, /const MAX_VISIBLE_TURNS = 10/);
  assert.match(appJs, /const MAX_EXPANDED_VISIBLE_TURNS = 200/);
  assert.match(appJs, /const THREAD_HISTORY_TOP_LOAD_PX = 64/);
  assert.match(appJs, /Boolean\(incomingThread\.mobileOlderTurnsCursor\)/);
  assert.match(appJs, /Number\(incomingThread\.mobileOmittedTurnCount \|\| 0\) > 0/);
  assert.match(appJs, /preservedExpandedTurnCount \+= 1/);
  assert.match(appJs, /merged\.mobileOmittedTurnCount = Math\.max\(0, Number\(merged\.mobileOmittedTurnCount \|\| 0\) - preservedExpandedTurnCount\)/);
  assert.match(appJs, /function loadOlderThreadTurns\(options = \{\}\)/);
  assert.match(appJs, /const preserveScroll = Boolean\(options\.preserveScroll\)/);
  assert.match(appJs, /let newlyLoadedTurnCount = 0/);
  assert.match(appJs, /if \(!existingTurn\) newlyLoadedTurnCount \+= 1/);
  assert.match(appJs, /state\.currentThread\.mobileOmittedTurnCount = Math\.max\(0, Number\(state\.currentThread\.mobileOmittedTurnCount \|\| 0\) - newlyLoadedTurnCount\)/);
  assert.match(appJs, /renderCurrentThread\(\{ stickToBottom: false \}\)/);
  assert.match(appJs, /preserveConversationScrollAfterPrepend\(previousScrollTop, previousScrollHeight\)/);
  assert.match(appJs, /function maybeLoadOlderThreadTurnsFromScroll\(\)/);
  assert.match(appJs, /conversation\.scrollTop > THREAD_HISTORY_TOP_LOAD_PX/);
  assert.match(appJs, /loadOlderThreadTurns\(\{ preserveScroll: true, source: "scroll-top" \}\)/);
  assert.match(appJs, /maybeLoadOlderThreadTurnsFromScroll\(\);/);
  assert.match(appJs, /data-load-older-turns/);
  assert.match(appJs, /loadOlderThreadTurns\(\{ preserveScroll: true, source: "button" \}\)/);
  assert.match(appJs, /cursor: threadTurnsCursorParam\(cursor\)/);
  assert.match(appJs, /mobileHistoryExpanded = true/);
  assert.match(stylesCss, /\.history-loader\s*{[\s\S]*justify-content:\s*space-between;/);
  assert.match(stylesCss, /\.history-load-button/);
  assert.match(swJs, /"\/api-client\.js"/);
  assert.match(swJs, /"\/runtime-settings\.js"/);
  assert.match(swJs, /"\/draft-store\.js"/);
  assert.match(swJs, /"\/markdown-renderer\.js"/);
  assert.match(swJs, /"\/viewport-metrics\.js"/);
  assert.match(swJs, /"\/conversation-scroll\.js"/);
  assert.match(swJs, /"\/image-compressor\.js"/);
  assert.match(swJs, /"\/plugin-embed\.js"/);
  assert.match(swJs, /"\/build-refresh-policy\.js"/);
  assert.match(appJs, /"\/viewport-metrics\.js"/);
  assert.match(appJs, /"\/conversation-scroll\.js"/);
  assert.match(appJs, /"\/image-compressor\.js"/);
  assert.match(appJs, /"\/plugin-embed\.js"/);
  assert.match(appJs, /"\/build-refresh-policy\.js"/);
  assert.match(appJs, /navigator\.serviceWorker\.register\("\/sw\.js"\)/);
  assert.match(appJs, /state\.serviceWorkerRegistration\.update\(\)\.catch/);
  assert.match(swJs, /if \(!data\.threadId && payload\.threadId\) data\.threadId = payload\.threadId;/);
  assert.match(swJs, /if \(threadId && !url\.searchParams\.get\("thread"\)\) \{/);
  assert.match(swJs, /url\.searchParams\.set\("thread", threadId\);/);
  assert.match(swJs, /self\.clients\.openWindow\(target\.url\)/);
  assert.match(indexHtml, /id="workspaceTokenUsage"/);
  assert.match(indexHtml, /id="workspaceStatsDialog"/);
  assert.match(appJs, /workspaceTokenUsage: null/);
  assert.match(appJs, /function renderWorkspaceTokenUsage\(\)/);
  assert.match(appJs, /function renderWorkspaceStatsDialog\(\)/);
  assert.match(appJs, /data-workspace-token-usage-toggle>统计<\/button>/);
  assert.match(appJs, /function formatTokenMillion\(value\)/);
  assert.match(appJs, /const THREAD_LIST_PAGE_LIMIT = 40;/);
  assert.match(appJs, /new URLSearchParams\(\{ limit: String\(THREAD_LIST_PAGE_LIMIT\), archived: "false" \}\)/);
  assert.match(appJs, /Uncached \$\{escapeHtml\(formatTokenMillion\(displayInputTokensExcludingCached\(entry\)\)\)\}/);
  assert.match(appJs, /Cached \$\{escapeHtml\(formatTokenMillion\(entry && entry\.cachedInputTokens\)\)\}/);
  assert.match(appJs, /Out \$\{escapeHtml\(formatTokenMillion\(entry && entry\.outputTokens\)\)\}/);
  assert.match(appJs, /Reason \$\{escapeHtml\(formatTokenMillion\(entry && entry\.reasoningOutputTokens\)\)\}/);
  assert.match(stylesCss, /\.workspace-token-usage/);
  assert.match(stylesCss, /\.workspace-token-usage-summary span[\s\S]*color:\s*var\(--danger-text\)/);
  assert.match(stylesCss, /\.workspace-stats-dialog/);
  assert.match(stylesCss, /\.workspace-stats-breakdown/);
});

test("Android back and edge swipe open the mobile navigation menu", () => {
  assert.match(appJs, /const ANDROID_SIDEBAR_EDGE_SWIPE_PX = 84/);
  assert.match(appJs, /const ANDROID_BACK_SIDEBAR_BASE = "base"/);
  assert.match(appJs, /const ANDROID_BACK_SIDEBAR_TOP = "top"/);
  assert.match(appJs, /function isAndroidBrowser\(\)/);
  assert.match(appJs, /function sidebarEdgeSwipeStartLimitPx\(\)/);
  assert.match(appJs, /touch\.clientX > sidebarEdgeSwipeStartLimitPx\(\)/);
  assert.match(appJs, /ensureAndroidBackToSidebarSentinel\(\);[\s\S]*if \(event\.cancelable !== false\) event\.preventDefault\(\);/);
  assert.match(appJs, /if \(event\.cancelable !== false\) event\.preventDefault\(\);/);
  assert.match(appJs, /addEventListener\("touchstart", beginSidebarEdgeSwipe, \{ passive: false \}\)/);
  assert.match(appJs, /function ensureAndroidBackToSidebarSentinel\(\)/);
  assert.match(appJs, /\$\("app"\)\.classList\.remove\("hidden"\);[\s\S]*ensureAndroidBackToSidebarSentinel\(\);/);
  assert.match(appJs, /window\.history\.replaceState\(Object\.assign\(\{\}, currentState,[\s\S]*ANDROID_BACK_SIDEBAR_BASE/);
  assert.match(appJs, /window\.history\.pushState\(Object\.assign\(\{\}, currentState,[\s\S]*ANDROID_BACK_SIDEBAR_TOP/);
  assert.match(appJs, /function handleAndroidBackToSidebarPopState\(event\)/);
  assert.match(appJs, /&& state\.key/);
  assert.match(appJs, /&& !app\.classList\.contains\("hidden"\)/);
  assert.match(appJs, /if \(!isSidebarOpen\(\)\) openSidebarMenu\(\);/);
  assert.match(appJs, /if \(document\.visibilityState === "visible"\) \{[\s\S]*ensureAndroidBackToSidebarSentinel\(\);/);
  assert.match(appJs, /window\.addEventListener\("pageshow",[\s\S]*ensureAndroidBackToSidebarSentinel\(\);/);
  assert.match(appJs, /window\.addEventListener\("focus",[\s\S]*ensureAndroidBackToSidebarSentinel\(\);/);
  assert.match(appJs, /window\.addEventListener\("popstate", handleAndroidBackToSidebarPopState\)/);
});

test("workspace creation lives at the bottom of the Workspace menu", () => {
  assert.match(indexHtml, /id="workspaceSelectMenu"/);
  assert.match(indexHtml, /id="newThreadButton"/);
  assert.match(indexHtml, /id="createWorkspaceDialog"/);
  assert.match(indexHtml, /id="createWorkspaceForm"/);
  assert.match(appJs, /function workspaceSidebarOptionsHtml\(\)/);
  assert.match(appJs, /data-create-workspace/);
  assert.match(appJs, /return allOption \+ workspaceOptions \+ createOption;/);
  assert.match(appJs, /openCreateWorkspaceDialog\(\)/);
  assert.match(appJs, /api\("\/api\/workspaces", \{[\s\S]*method: "POST"/);
  assert.match(stylesCss, /\.workspace-create-option/);
  assert.doesNotMatch(indexHtml, /newThreadButton[\s\S]{0,240}createWorkspace/i);
});

test("push notification control stays hidden when the browser cannot enable it", () => {
  assert.doesNotMatch(appJs, /HTTPS required/);
  assert.doesNotMatch(appJs, /Notifications unavailable/);
  assert.doesNotMatch(appJs, /Notifications unsupported/);
  assert.match(appJs, /const hideButton = \(\) => \{/);
  assert.match(appJs, /if \(!window\.isSecureContext\) \{[\s\S]*hideButton\(\);[\s\S]*return;[\s\S]*\}/);
});
